#!/bin/sh
# build_samples.sh -- the x86-64 ABI course: build every input, run the
# artifact, and cross-check the result against a FRESH run.
#
#   ./build_samples.sh            build, run, cross-check
#   ./build_samples.sh --quick    fewer iterations in the timing section
#
# The cross-check runs against a FRESH run, not against the committed
# abidump.out, so that "the claims still hold on this machine today" is a
# statement about the machine and not a tautology about a checked-in file.
#
# FIVE THINGS ARE PRODUCED HERE, and abidump.c reads all five:
#
#   abi_dis.txt     the corpus compiled at -O0/-O1/-O2/-Os, LINKED, and read
#                   back by mkabi.py, which recovers which SOURCE went into
#                   which REGISTER by name.  A .o is not enough: in a .o every
#                   RIP-relative load reads [rip+0x0] and the identity of the
#                   argument is not in the file at all.
#   abi_cfi.txt     the .cfi_* directives gcc emitted, the number of FDEs with
#                   and without -fno-asynchronous-unwind-tables, and the size
#                   of .eh_frame in each case.  The frame described twice.
#   abi_control.txt abilint.py's verdict on control.s, which was written to be
#                   caught.  Without it every zero in this file is a hollow
#                   zero, and the first version of the linter produced five.
#   abi_libc.txt    abilint.py's verdict on a real glibc: 4,561 functions.
#   abidump.out     the artifact's own output, which is what ships.
#
# The unwinding probe is built TWICE, with and without unwind tables, and
# abidump.c RUNS both and reads the frame counts off their output.  The number
# in the course is therefore produced by glibc's unwinder and not typed in by
# an author.
set -e
cd "$(dirname "$0")"

CC=${CC:-cc}
CFLAGS=${CFLAGS:--O2 -Wall -Wextra}
OBJDUMP=${OBJDUMP:-objdump}
READELF=${READELF:-readelf}
# The audited library.  libc.a rather than libc.so.6 because the audit needs
# each function's EXTENT, and a stripped shared library has no symbol sizes.
# If it is not here the artifact says so and runs without it rather than
# printing an empty table that reads like a result.
LIBA=${LIBA:-/usr/lib/x86_64-linux-gnu/libc.a}

echo "==> toolchain"
$CC --version | head -1
$OBJDUMP --version | head -1
as --version | head -1

# ------------------------------------------------------------------
# 1. the hand-written half
# ------------------------------------------------------------------
echo "==> assembling abis.s"
# .S and not .s, because the file uses a CPP constant; `as` alone does not
# run the preprocessor and the constant would become an undefined symbol.
$CC -c -o abis.o abis.S
$CC -c -o control.o control.s
echo "    abis.o: $(grep -c '^\s*\.globl' abis.s) entry points, control.o built"

# ------------------------------------------------------------------
# 2. the corpus, four optimisation levels, LINKED, read back
# ------------------------------------------------------------------
echo "==> corpus at -O0 -O1 -O2 -Os"
cat > _stubs.c <<'STUBEOF'
void abi_sink(long x)   { __asm__ __volatile__("" :: "r"(x) : "memory"); }
void abi_sinkd(double x){ __asm__ __volatile__("" :: "x"(x) : "memory"); }
int  main(void) { return 0; }
STUBEOF
rm -f abi_dis.txt
for O in 0 1 2 s; do
    $CC -O$O -c -o _c$O.o abidump_corpus.c
    $CC -O$O -o _x$O _c$O.o _stubs.c
    python3 mkabi.py _x$O abi_dis.txt O$O
done
rm -f _stubs.c _c0.o _c1.o _c2.o _cs.o

# ------------------------------------------------------------------
# 3. the second description of the frame
# ------------------------------------------------------------------
echo "==> the .cfi_* directives, and .eh_frame with and without them"
$CC -O2 -S -o _cfi.s abidump_corpus.c
{
  echo "# abi_cfi.txt -- GENERATED by build_samples.sh.  Do not hand-edit."
  echo "# THE FRAME, DESCRIBED IN A SECOND LANGUAGE.  The first description is"
  echo "# the instructions; this one is a table that says where the Canonical"
  echo "# Frame Address is at every program counter in the function, and a"
  echo "# register-by-register map of what to restore to unwind past it."
  echo "TOOL | $CC -O2 -S | $CC --version | head -1"
  printf 'DIRECTIVE | cfi_startproc | %s\n' "$(grep -c '\.cfi_startproc' _cfi.s)"
  printf 'DIRECTIVE | cfi_endproc | %s\n'   "$(grep -c '\.cfi_endproc' _cfi.s)"
  printf 'DIRECTIVE | cfi_def_cfa_offset | %s\n' "$(grep -c '\.cfi_def_cfa_offset' _cfi.s)"
  printf 'DIRECTIVE | cfi_def_cfa_register | %s\n' "$(grep -c '\.cfi_def_cfa_register' _cfi.s)"
  printf 'DIRECTIVE | cfi_offset | %s\n' "$(grep -c '\.cfi_offset' _cfi.s)"
  printf 'DIRECTIVE | cfi_scfn | %s\n' "$(grep -c '\.cfi_restore' _cfi.s)"
  printf 'DIRECTIVE | total | %s\n' "$(grep -o '\.cfi_[a-z_0-9]*' _cfi.s | wc -l)"
  # Three bodies, not two.  The first draft of the course asserted a frame
  # description costs "about ELEVEN bytes without a frame pointer and about
  # FORTY with one".  Only the first half was ever measured, and the second
  # was an estimate presented as a figure.  Compiling the same corpus three
  # ways settles it: -fomit-frame-pointer and the default are BYTE-IDENTICAL
  # (gcc omits frame pointers at -O2 anyway, so the flag confirms a default
  # rather than changing anything), and -fno-omit-frame-pointer is the number
  # that was guessed.  It is not forty.  See section 8 of abidump.out.
  for SPEC in "with:" "without:-fno-asynchronous-unwind-tables" \
              "fp_omitted:-fomit-frame-pointer" "fp_kept:-fno-omit-frame-pointer"; do
    LBL=${SPEC%%:*}
    FLAG=${SPEC#*:}
    $CC -O2 $FLAG -c -o _eh.o abidump_corpus.c
    printf 'FDE | %s | %s\n' "$LBL" "$($READELF --debug-dump=frames _eh.o 2>/dev/null | grep -c 'FDE cie=')"
    printf 'EHSIZE | %s | %s\n' "$LBL" \
      "$($READELF -S _eh.o 2>/dev/null | awk '/\.eh_frame/{getline; print $1}' | head -1 | sed 's/^0*//;s/^$/0/')"
  done
  rm -f _eh.o
} > abi_cfi.txt
rm -f _cfi.s
grep -E '^(DIRECTIVE|FDE|EHSIZE)' abi_cfi.txt | sed 's/^/    /'

# ------------------------------------------------------------------
# 4. the unwinding probe, built twice
# ------------------------------------------------------------------
echo "==> uwprobe, with and without asynchronous unwind tables"
$CC -O1 -rdynamic -o uwprobe_yes uwprobe.c -DUNW_TABLES='"yes"'
$CC -O1 -rdynamic -fno-asynchronous-unwind-tables -o uwprobe_no uwprobe.c -DUNW_TABLES='"no"'
printf '  uwprobe_yes  : %s\n' "$(./uwprobe_yes | tr '\n' ' ')"
printf '  uwprobe_no   : %s\n' "$(./uwprobe_no  | tr '\n' ' ')"
# The two frame counts are RECORDED HERE, by the real unwinder, into the file
# the artifact reads.  The first version had abidump popen() the probes at run
# time and it read NOTHING: popen() returned a valid stream, the child wrote
# nothing into it, and the section printed "FRAMES -1" and carried on.  A
# generated input is a better shape for this, because a missing input is
# visible in the file and a failed popen is not.
printf 'BACKTRACE | with | %s\n'       "$(./uwprobe_yes | awk '/^FRAMES/{print $2}')"     >> abi_cfi.txt
printf 'BACKTRACE | depth_with | %s\n' "$(./uwprobe_yes | awk '/^STACKDEPTH/{print $2}')" >> abi_cfi.txt
printf 'BACKTRACE | without | %s\n'    "$(./uwprobe_no  | awk '/^FRAMES/{print $2}')"     >> abi_cfi.txt
printf 'BACKTRACE | depth_without | %s\n' "$(./uwprobe_no | awk '/^STACKDEPTH/{print $2}')" >> abi_cfi.txt

# ------------------------------------------------------------------
# 5. the linter, on the control and on a real library
# ------------------------------------------------------------------
echo "==> abilint.py on control.s (built to be caught)"
python3 abilint.py --control control.o
grep -E '^(CLAPPER|ALIGNCALLS)' abi_control.txt | sed 's/^/    /'

echo "==> abilint.py on $LIBA"
if [ -f "$LIBA" ]; then
    python3 abilint.py --lib "$LIBA"
    grep -E '^(LIBRARY|FUNCTIONS|CLOBBERFLAGS|CLOBBERKIND|ALIGN)' abi_libc.txt | sed 's/^/    /'
else
    echo "    NOT PRESENT at $LIBA -- writing a file that says so"
    {
      echo "# abi_libc.txt -- GENERATED.  The audited library was not present."
      echo "ABSENT | $LIBA"
    } > abi_libc.txt
fi

# ------------------------------------------------------------------
# 6. build and run the artifact
# ------------------------------------------------------------------
echo "==> building abidump with: $CC $CFLAGS"
$CC $CFLAGS -o abidump abidump.c abis.o

if [ "$1" = "--quick" ]; then
    OUT=/tmp/opencode/abidump.quick.$$
    echo "==> quick run"
    ./abidump --quick > "$OUT"
else
    OUT=abidump.out
    echo "==> running abidump"
    ./abidump > "$OUT"
fi

echo "==> cross-checking $OUT"
python3 crosscheck.py "$OUT"
rc=$?

if [ "$1" != "--quick" ]; then
    echo
    echo "==> the results, on their own, because a harness that can only be"
    echo "    read inside a transcript is a harness nobody reads."
    echo
    sed -n '/THE AUDIT, PER OPTIMISATION LEVEL/,/^$/p'      "$OUT" | sed 's/^/  AUD /'
    sed -n '/WHERE THE RETURN ADDRESS ACTUALLY IS/,/^$/p'   "$OUT" | sed 's/^/  RET /'
    sed -n '/THE ALIGNMENT FAULT/,/^$/p'                   "$OUT" | sed 's/^/  ALN /'
    sed -n '/THE RED ZONE, MEASURED/,/^$/p'               "$OUT" | sed 's/^/  RDZ /'
    sed -n '/CALLEE-SAVED, BY EXPERIMENT/,/^$/p'           "$OUT" | sed 's/^/  SAV /'
    sed -n '/THE VARARGS REGISTER SAVE AREA/,/^$/p'        "$OUT" | sed 's/^/  VAR /'
    sed -n '/WHAT A PROFILER CAN AND CANNOT SEE/,/^$/p'    "$OUT" | sed 's/^/  UNW /'
    sed -n '/THE AUDIT OF A REAL LIBRARY/,/^$/p'          "$OUT" | sed 's/^/  LIB /'
    sed -n '/^RETRACTIONS/,/^LIMITS/p'                    "$OUT" | sed 's/^/  RETR/'
fi
exit $rc
