#!/bin/sh
# build_samples.sh -- the x86simd course: build every input, run the
# artifact three times, and cross-check a FRESH run rather than the
# committed one.
#
#   ./build_samples.sh            build, run three times, cross-check
#   ./build_samples.sh --quick    fewer iterations in the timing sections
#
# The cross-check runs against a FRESH run, so that "the claims still hold
# on this machine today" is a statement about the machine and not a
# tautology about a checked-in file.
#
# FOUR THINGS ARE PRODUCED HERE, and two of them exist only because an
# instrument was wrong and a retraction with the instruction beside it is
# worth more than a retraction with the word `movaps` in it:
#
#   vecmaps.bin / vecmaps_dis.txt
#                     the thirty encodings, produced by the artifact's own
#                     ENCODER and assembled verbatim, so objdump reads
#                     BYTES THIS FILE EMITTED rather than bytes someone
#                     typed into a .s file.  This is the SECOND READER
#                     for R9: the round trip agreed with itself and
#                     binutils did not.
#   vecdump_dis.txt   objdump of the bodies section 2 and section 5 claim
#                     things about.  It exists for R7 (the intrinsics
#                     version of the SSE body compiled to VEX, so the
#                     vzeroupper experiment measured the wrong bytes) and
#                     for R11 (a probe the compiler deleted also 'returns').
#   vecdump.out       the artifact's own output, which is what ships.
#   run1.txt run2.txt two more runs, so a reader can see which numbers
#                     move between runs and which do not.
set -e
cd "$(dirname "$0")"

CC=${CC:-cc}
OBJDUMP=${OBJDUMP:-objdump}

# The vector flags are NOT optional and the reason is worth saying out
# loud: without -mavx2 gcc emits SSE2 and NOT ONE of the instructions
# this artifact is trying to measure appears in the binary.  The SIMD
# course lost an entire experiment to a build flag, and section 1's
# instruction census plus the disassembly below are what make the flag
# checkable rather than a claim.
CFLAGS="-O2 -Wall -Wextra -mavx2 -mfma"
SRCS="veccore.c vec1.c vec2.c vec3b.c vec4.c vec5.c vecmaps.c vec7.c"

echo "==> toolchain"
$CC --version | head -1
$OBJDUMP --version | head -1
echo "==> CFLAGS: $CFLAGS"

# ------------------------------------------------------------------
# 1. build
# ------------------------------------------------------------------
echo "==> building vecdump"
$CC $CFLAGS -o vecdump $SRCS -lpthread

# ------------------------------------------------------------------
# 2. the second reader: the encoder's OWN bytes, assembled and read back
# ------------------------------------------------------------------
echo "==> vecmaps.bin, emitted by the artifact's own encoder"
./vecdump --emit-maps
{
    echo "# vecmaps_dis.txt -- GENERATED by build_samples.sh.  Do not edit."
    echo "# objdump of the bytes vecmap.c's ENCODER produced, assembled"
    echo "# verbatim.  This is the SECOND READER that caught R9: the round"
    echo "# trip agreed with itself and binutils did not."
    $OBJDUMP -D -b binary -m i386:x86-64 vecmaps.bin |
        sed -n '/<.data>:/,$p' |
        sed 's/^/  MAP | /'
} > vecmaps_dis.txt
sed -n '4,7p' vecmaps_dis.txt | sed 's/^/    /'

# ------------------------------------------------------------------
# 3. the disassembly the other retractions depend on
# ------------------------------------------------------------------
echo "==> vecdump_dis.txt"
{
    echo "# vecdump_dis.txt -- GENERATED by build_samples.sh.  Do not edit."
    echo "# (a) the alignment probe bodies, section 2.  These bytes are"
    echo "#     the evidence for R8: the first probe used the \"m\""
    echo "#     constraint on a double[4] and gcc emitted a safe sequence,"
    echo "#     so four of the ten rows reported 'returned' on a"
    echo "#     deliberately misaligned address."
    $OBJDUMP -d --no-show-raw-insn vecdump 2>/dev/null |
        sed -n '/<p_apd_load>:/,/^$/p' | sed 's/^/  /'
    $OBJDUMP -d --no-show-raw-insn vecdump 2>/dev/null |
        sed -n '/<p_ups_load>:/,/^$/p' | sed 's/^/  /'
    $OBJDUMP -d --no-show-raw-insn vecdump 2>/dev/null |
        sed -n '/<p_aps_load>:/,/^$/p' | sed 's/^/  /'
    echo "# (b) the LEGACY-encoded SSE body, section 3C.  These bytes are"
    echo "#     the whole of R7: with intrinsics gcc emits c5 f8 58 c1,"
    echo "#     which is VEX and has no transition penalty at all."
    $OBJDUMP -d --no-show-raw-insn vecdump 2>/dev/null |
        sed -n '/<sse_legacy>:/,/^$/p' | sed 's/^/  /'
    echo "# (c) the VEX-encoded control: the same arithmetic, same loop."
    $OBJDUMP -d --no-show-raw-insn vecdump 2>/dev/null |
        sed -n '/<sse_vex>:/,/^$/p' | sed 's/^/  /'
    echo "# (d) the 256-bit body, and note the vzeroupper gcc adds by"
    echo "#     itself, which is a compiler decision and not a hardware one."
    $OBJDUMP -d --no-show-raw-insn vecdump 2>/dev/null |
        sed -n '/<avx_body>:/,/^$/p' | sed 's/^/  /'
    echo "# (e) the ATOMIC arms.  The harness asserts that an f0 byte is"
    echo "#     present on every LOCK arm and ABSENT on every no-LOCK arm,"
    echo "#     which is R11: a probe the compiler deleted also 'returns'."
    $OBJDUMP -d --no-show-raw-insn vecdump 2>/dev/null |
        sed -n '/<c_lock_add>:/,/^$/p' | sed 's/^/  /'
    $OBJDUMP -d --no-show-raw-insn vecdump 2>/dev/null |
        sed -n '/<c_plain_add>:/,/^$/p' | sed 's/^/  /'
    $OBJDUMP -d --no-show-raw-insn vecdump 2>/dev/null |
        sed -n '/<c_lock_cas16b>:/,/^$/p' | sed 's/^/  /'
    echo "# (f) the three fences, and the claim in section 5B is that they"
    echo "#     are three bytes differing in the ModRM reg field alone."
    $OBJDUMP -d --no-show-raw-insn vecdump 2>/dev/null |
        grep -E "sfence|lfence|mfence" | sed 's/^/  /'
    echo "# (g) the string-direction bodies, section 5C.  Both arms must"
    echo "#     carry the instruction; the harness checks the std and the"
    echo "#     cld are there as well as the rep movsb."
    $OBJDUMP -d --no-show-raw-insn vecdump 2>/dev/null |
        sed -n '/<up256>:/,/^$/p' | grep -E "rep|cld|std" | sed 's/^/  /'
    $OBJDUMP -d --no-show-raw-insn vecdump 2>/dev/null |
        sed -n '/<dn256>:/,/^$/p' | grep -E "rep|cld|std" | sed 's/^/  /'
} > vecdump_dis.txt
sed -n '3,9p' vecdump_dis.txt | sed 's/^/    /'

# ------------------------------------------------------------------
# 4. run three times
# ------------------------------------------------------------------
if [ "$1" = "--quick" ]; then
    echo "==> quick run"
    ./vecdump --quick > /tmp/opencode/vecdump.quick.$$
else
    echo "==> run 1"
    ./vecdump --dis > vecdump.out
    echo "==> run 2"
    ./vecdump --dis > run1.txt
    echo "==> run 3"
    ./vecdump --dis > run2.txt
fi

# ------------------------------------------------------------------
# 5. cross-check a fresh run
# ------------------------------------------------------------------
echo "==> cross-checking a FRESH run"
./vecdump --dis ${1:---full} > /tmp/opencode/vecdump.fresh.$$
set +e
python3 crosscheck.py /tmp/opencode/vecdump.fresh.$$
rc=$?
set -e

if [ "$1" != "--quick" ]; then
    echo
    echo "==> the results, on their own, because a harness that can only be"
    echo "    read inside a transcript is a harness nobody reads."
    echo
    sed -n '/^2\.  ALIGNMENT/,/AND THE VEX ROW/p'   vecdump.out | sed 's/^/  ALI /'
    sed -n '/^  DIRTY |/,/TWO vzeroupper/p'        vecdump.out | sed 's/^/  DRT /'
    sed -n '/^  CNT  |/,/^  -----+---/p'            vecdump.out | sed 's/^/  CNT /'
    sed -n '/^  PAIR |/,/^  -----+---/p'            vecdump.out | sed 's/^/  PR  /'
    sed -n '/^  IDENT|/,/^  -----+---/p'            vecdump.out | sed 's/^/  ID  /'
    sed -n '/^  ORD  |/,/other floor/p'             vecdump.out | sed 's/^/  ORD /'
    sed -n '/bytes |   DF=0/,/^  -----+----/p'     vecdump.out | sed 's/^/  DF  /'
    sed -n '/^  MAP  |/,/^  ----/p'                vecdump.out | sed 's/^/  MAP /'
    sed -n '/^   R1\./,/^  R2[0-9]\./p'             vecdump.out | sed 's/^/  RET /'
fi
exit $rc
