// underlayer_repository — Schema initialization.
using std::string
using underlayer_db::DbClient

public namespace underlayer_repository {

    public func init_schema(db : *DbClient) {
        var sql = string("CREATE TABLE IF NOT EXISTS learners (id TEXT PRIMARY KEY, name TEXT, email TEXT UNIQUE, password_hash TEXT, created_at INTEGER)")
        underlayer_db::exec_sql(db, &raw sql)
        // 16.2.1: Add password_hash column for existing DBs
        var mig_ph = string("ALTER TABLE learners ADD COLUMN password_hash TEXT")
        underlayer_db::exec_sql(db, &raw mig_ph)
        var sql2 = string("CREATE TABLE IF NOT EXISTS concept_states (learner_id TEXT, concept_id TEXT, course_id TEXT, status TEXT DEFAULT 'not_started', attempts INTEGER DEFAULT 0, correct INTEGER DEFAULT 0, streak INTEGER DEFAULT 0, last_studied INTEGER, next_review INTEGER, difficulty_rating REAL DEFAULT 0, PRIMARY KEY (learner_id, concept_id, course_id))")
        underlayer_db::exec_sql(db, &raw sql2)
        var sql3 = string("CREATE TABLE IF NOT EXISTS review_items (id TEXT PRIMARY KEY, learner_id TEXT, concept_id TEXT, course_id TEXT, type TEXT, front TEXT, back TEXT, difficulty REAL DEFAULT 5.0, stability REAL DEFAULT 1.0, retrievability REAL DEFAULT 1.0, next_review INTEGER, last_review INTEGER, reps INTEGER DEFAULT 0, lapses INTEGER DEFAULT 0, ease_factor REAL DEFAULT 2.5)")
        underlayer_db::exec_sql(db, &raw sql3)
        // 1.1.15: Add ease_factor column if missing (migration for existing DBs)
        var mig = string("ALTER TABLE review_items ADD COLUMN ease_factor REAL DEFAULT 2.5")
        underlayer_db::exec_sql(db, &raw mig)
        var sql4 = string("CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, learner_id TEXT, start_time INTEGER, end_time INTEGER, type TEXT, exercises_attempted INTEGER DEFAULT 0, exercises_correct INTEGER DEFAULT 0, status TEXT DEFAULT 'active')")
        underlayer_db::exec_sql(db, &raw sql4)
        var sql5 = string("CREATE TABLE IF NOT EXISTS session_items (id INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT, concept_id TEXT, rating INTEGER, time_spent_ms INTEGER, reviewed_at INTEGER)")
        underlayer_db::exec_sql(db, &raw sql5)
        // 4.1.1-4.1.5: Exercise table
        var sql6 = string("CREATE TABLE IF NOT EXISTS exercises (id TEXT PRIMARY KEY, concept_id TEXT, type TEXT, question TEXT, answer TEXT, options_json TEXT, correct_index INTEGER DEFAULT 0, explanation TEXT, hint1 TEXT, hint2 TEXT, hint3 TEXT, difficulty REAL DEFAULT 0.5)")
        underlayer_db::exec_sql(db, &raw sql6)
        // 4.1.3: Add correct_indices column for multi-select exercises
        var sql6b = string("ALTER TABLE exercises ADD COLUMN correct_indices_json TEXT DEFAULT '[]'")
        underlayer_db::exec_sql(db, &raw sql6b)
        var idx1 = string("CREATE INDEX IF NOT EXISTS idx_cs_learner ON concept_states(learner_id)")
        underlayer_db::exec_sql(db, &raw idx1)
        var idx2 = string("CREATE INDEX IF NOT EXISTS idx_ri_learner ON review_items(learner_id)")
        underlayer_db::exec_sql(db, &raw idx2)
        var idx3 = string("CREATE INDEX IF NOT EXISTS idx_ri_due ON review_items(next_review)")
        underlayer_db::exec_sql(db, &raw idx3)
        var idx4 = string("CREATE INDEX IF NOT EXISTS idx_sess_learner ON sessions(learner_id)")
        underlayer_db::exec_sql(db, &raw idx4)
        var idx5 = string("CREATE INDEX IF NOT EXISTS idx_si_session ON session_items(session_id)")
        underlayer_db::exec_sql(db, &raw idx5)
        // 6.1.5: Learning goals table
        var sql7 = string("CREATE TABLE IF NOT EXISTS learning_goals (id TEXT PRIMARY KEY, learner_id TEXT, course_id TEXT, target_date INTEGER, created_at INTEGER)")
        underlayer_db::exec_sql(db, &raw sql7)
        var idx6 = string("CREATE INDEX IF NOT EXISTS idx_lg_learner ON learning_goals(learner_id)")
        underlayer_db::exec_sql(db, &raw idx6)
        // 16.5: Learner profiles
        var sql8 = string("CREATE TABLE IF NOT EXISTS learner_profiles (learner_id TEXT PRIMARY KEY, display_name TEXT, username TEXT UNIQUE, avatar_url TEXT, bio TEXT, learning_goals TEXT, location TEXT, website TEXT, social_twitter TEXT, social_github TEXT, social_linkedin TEXT, visibility TEXT DEFAULT 'public', username_changed_at INTEGER DEFAULT 0, created_at INTEGER, updated_at INTEGER)")
        underlayer_db::exec_sql(db, &raw sql8)
        // 16.6: Learner settings
        var sql9 = string("CREATE TABLE IF NOT EXISTS learner_settings (learner_id TEXT PRIMARY KEY, theme TEXT DEFAULT 'system', font_size TEXT DEFAULT 'medium', language TEXT DEFAULT 'en', timezone TEXT DEFAULT 'UTC', date_format TEXT DEFAULT 'YYYY-MM-DD', email_notifications INTEGER DEFAULT 1, push_notifications INTEGER DEFAULT 1, in_app_notifications INTEGER DEFAULT 1, compact_mode INTEGER DEFAULT 0, created_at INTEGER, updated_at INTEGER)")
        underlayer_db::exec_sql(db, &raw sql9)
        // 16.7: Learning preferences
        var sql10 = string("CREATE TABLE IF NOT EXISTS learning_preferences (learner_id TEXT PRIMARY KEY, daily_goal_minutes INTEGER DEFAULT 20, daily_review_items INTEGER DEFAULT 10, session_length_minutes INTEGER DEFAULT 30, break_reminder_minutes INTEGER DEFAULT 25, preferred_session_time TEXT DEFAULT 'flexible', energy_checkin INTEGER DEFAULT 1, difficulty_preference TEXT DEFAULT 'auto', interleaving_preference TEXT DEFAULT 'auto', review_scheduling TEXT DEFAULT 'flexible', show_streaks INTEGER DEFAULT 1, show_leaderboards INTEGER DEFAULT 1, show_achievements INTEGER DEFAULT 1, auto_play_audio INTEGER DEFAULT 0, created_at INTEGER, updated_at INTEGER)")
        underlayer_db::exec_sql(db, &raw sql10)
        // 16.10.1: Login history
        var sql11 = string("CREATE TABLE IF NOT EXISTS login_history (id INTEGER PRIMARY KEY AUTOINCREMENT, learner_id TEXT, ip_address TEXT, user_agent TEXT, success INTEGER DEFAULT 1, failure_reason TEXT, created_at INTEGER)")
        underlayer_db::exec_sql(db, &raw sql11)
        // 16.2.14: Sessions (JWT tokens)
        var sql12 = string("CREATE TABLE IF NOT EXISTS auth_sessions (id TEXT PRIMARY KEY, learner_id TEXT, token_hash TEXT, device_info TEXT, ip_address TEXT, expires_at INTEGER, last_active INTEGER, created_at INTEGER)")
        underlayer_db::exec_sql(db, &raw sql12)
        // 16.3.3: Password reset tokens
        var sql13 = string("CREATE TABLE IF NOT EXISTS password_reset_tokens (id TEXT PRIMARY KEY, learner_id TEXT, token_hash TEXT, expires_at INTEGER, used INTEGER DEFAULT 0, created_at INTEGER)")
        underlayer_db::exec_sql(db, &raw sql13)
        // 16.4.2: Email verification tokens
        var sql14 = string("CREATE TABLE IF NOT EXISTS email_verification_tokens (id TEXT PRIMARY KEY, learner_id TEXT, email TEXT, token_hash TEXT, expires_at INTEGER, used INTEGER DEFAULT 0, created_at INTEGER)")
        underlayer_db::exec_sql(db, &raw sql14)
        // 16.10.7: API keys
        var sql15 = string("CREATE TABLE IF NOT EXISTS api_keys (id TEXT PRIMARY KEY, learner_id TEXT, key_hash TEXT, name TEXT, last_used_at INTEGER, expires_at INTEGER, created_at INTEGER)")
        underlayer_db::exec_sql(db, &raw sql15)
        // 16.10.14: Audit log
        var sql16 = string("CREATE TABLE IF NOT EXISTS audit_log (id INTEGER PRIMARY KEY AUTOINCREMENT, learner_id TEXT, action TEXT, details TEXT, ip_address TEXT, created_at INTEGER)")
        underlayer_db::exec_sql(db, &raw sql16)
        // Indexes for new tables
        var idx7 = string("CREATE INDEX IF NOT EXISTS idx_lp_learner ON learner_profiles(learner_id)")
        underlayer_db::exec_sql(db, &raw idx7)
        var idx8 = string("CREATE INDEX IF NOT EXISTS idx_ls_learner ON learner_settings(learner_id)")
        underlayer_db::exec_sql(db, &raw idx8)
        var idx9 = string("CREATE INDEX IF NOT EXISTS idx_lpref_learner ON learning_preferences(learner_id)")
        underlayer_db::exec_sql(db, &raw idx9)
        var idx10 = string("CREATE INDEX IF NOT EXISTS idx_lh_learner ON login_history(learner_id)")
        underlayer_db::exec_sql(db, &raw idx10)
        var idx11 = string("CREATE INDEX IF NOT EXISTS idx_as_learner ON auth_sessions(learner_id)")
        underlayer_db::exec_sql(db, &raw idx11)
        var idx12 = string("CREATE INDEX IF NOT EXISTS idx_as_token ON auth_sessions(token_hash)")
        underlayer_db::exec_sql(db, &raw idx12)
        var idx13 = string("CREATE INDEX IF NOT EXISTS idx_prt_learner ON password_reset_tokens(learner_id)")
        underlayer_db::exec_sql(db, &raw idx13)
        var idx14 = string("CREATE INDEX IF NOT EXISTS idx_prt_token ON password_reset_tokens(token_hash)")
        underlayer_db::exec_sql(db, &raw idx14)
        var idx15 = string("CREATE INDEX IF NOT EXISTS idx_evt_learner ON email_verification_tokens(learner_id)")
        underlayer_db::exec_sql(db, &raw idx15)
        var idx16 = string("CREATE INDEX IF NOT EXISTS idx_evt_token ON email_verification_tokens(token_hash)")
        underlayer_db::exec_sql(db, &raw idx16)
        var idx17 = string("CREATE INDEX IF NOT EXISTS idx_ak_learner ON api_keys(learner_id)")
        underlayer_db::exec_sql(db, &raw idx17)
        var idx18 = string("CREATE INDEX IF NOT EXISTS idx_ak_token ON api_keys(key_hash)")
        underlayer_db::exec_sql(db, &raw idx18)
        var idx19 = string("CREATE INDEX IF NOT EXISTS idx_al_learner ON audit_log(learner_id)")
        underlayer_db::exec_sql(db, &raw idx19)
        // 16.1.1: Add password_hash column if missing
        var mig_pw = string("ALTER TABLE learners ADD COLUMN password_hash TEXT DEFAULT ''")
        underlayer_db::exec_sql(db, &raw mig_pw)
        // 6.2.3: Course analytics
        var sql_ca = string("CREATE TABLE IF NOT EXISTS course_analytics (id INTEGER PRIMARY KEY AUTOINCREMENT, learner_id TEXT, course_id TEXT, total_concepts INTEGER DEFAULT 0, mastered_concepts INTEGER DEFAULT 0, learning_concepts INTEGER DEFAULT 0, completion_pct REAL DEFAULT 0, velocity_concepts_per_week REAL DEFAULT 0, total_time_seconds INTEGER DEFAULT 0, updated_at INTEGER)")
        underlayer_db::exec_sql(db, &raw sql_ca)
        var idx_ca = string("CREATE INDEX IF NOT EXISTS idx_ca_learner ON course_analytics(learner_id)")
        underlayer_db::exec_sql(db, &raw idx_ca)
        // 6.2.8: Difficulty analytics (per concept per learner)
        var sql_da = string("CREATE TABLE IF NOT EXISTS difficulty_analytics (id INTEGER PRIMARY KEY AUTOINCREMENT, learner_id TEXT, concept_id TEXT, avg_rating REAL DEFAULT 0, rating_count INTEGER DEFAULT 0, easy_count INTEGER DEFAULT 0, medium_count INTEGER DEFAULT 0, hard_count INTEGER DEFAULT 0, updated_at INTEGER)")
        underlayer_db::exec_sql(db, &raw sql_da)
        var idx_da = string("CREATE INDEX IF NOT EXISTS idx_da_learner ON difficulty_analytics(learner_id)")
        underlayer_db::exec_sql(db, &raw idx_da)
        // 6.2.9: Error analytics (common mistakes)
        var sql_ea = string("CREATE TABLE IF NOT EXISTS error_analytics (id INTEGER PRIMARY KEY AUTOINCREMENT, learner_id TEXT, concept_id TEXT, exercise_id TEXT, error_count INTEGER DEFAULT 0, last_error_at INTEGER, last_error_text TEXT)")
        underlayer_db::exec_sql(db, &raw sql_ea)
        var idx_ea = string("CREATE INDEX IF NOT EXISTS idx_ea_learner ON error_analytics(learner_id)")
        underlayer_db::exec_sql(db, &raw idx_ea)
        // 6.2.13: Engagement analytics (sessions per week)
        var sql_ena = string("CREATE TABLE IF NOT EXISTS engagement_analytics (id INTEGER PRIMARY KEY AUTOINCREMENT, learner_id TEXT, week_start INTEGER, sessions_count INTEGER DEFAULT 0, total_time_seconds INTEGER DEFAULT 0, concepts_studied INTEGER DEFAULT 0, exercises_attempted INTEGER DEFAULT 0, exercises_correct INTEGER DEFAULT 0)")
        underlayer_db::exec_sql(db, &raw sql_ena)
        var idx_ena = string("CREATE INDEX IF NOT EXISTS idx_ena_learner ON engagement_analytics(learner_id)")
        underlayer_db::exec_sql(db, &raw idx_ena)
        var idx_ena_w = string("CREATE INDEX IF NOT EXISTS idx_ena_learner_week ON engagement_analytics(learner_id, week_start)")
        underlayer_db::exec_sql(db, &raw idx_ena_w)
        // 6.2.14: Weekly velocity snapshot
        var sql_va = string("CREATE TABLE IF NOT EXISTS velocity_analytics (id INTEGER PRIMARY KEY AUTOINCREMENT, learner_id TEXT, week_start INTEGER, concepts_completed INTEGER DEFAULT 0, items_reviewed INTEGER DEFAULT 0, accuracy_pct REAL DEFAULT 0, streak_days INTEGER DEFAULT 0)")
        underlayer_db::exec_sql(db, &raw sql_va)
        var idx_va = string("CREATE INDEX IF NOT EXISTS idx_va_learner ON velocity_analytics(learner_id)")
        underlayer_db::exec_sql(db, &raw idx_va)
        var idx_va_w = string("CREATE INDEX IF NOT EXISTS idx_va_learner_week ON velocity_analytics(learner_id, week_start)")
        underlayer_db::exec_sql(db, &raw idx_va_w)
        // Course enrollments
        var sql_enroll = string("CREATE TABLE IF NOT EXISTS enrollments (id TEXT PRIMARY KEY, learner_id TEXT, course_id TEXT, enrolled_at INTEGER, last_accessed INTEGER, completed_at INTEGER, status TEXT DEFAULT 'active')")
        underlayer_db::exec_sql(db, &raw sql_enroll)
        var idx_enroll = string("CREATE INDEX IF NOT EXISTS idx_enroll_learner ON enrollments(learner_id)")
        underlayer_db::exec_sql(db, &raw idx_enroll)
        var idx_enroll_course = string("CREATE INDEX IF NOT EXISTS idx_enroll_course ON enrollments(course_id)")
        underlayer_db::exec_sql(db, &raw idx_enroll_course)
        // Notifications table
        var sql_notif = string("CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY, learner_id TEXT NOT NULL, type TEXT NOT NULL, title TEXT NOT NULL, message TEXT NOT NULL, course_id TEXT DEFAULT '', concept_id TEXT DEFAULT '', is_read INTEGER DEFAULT 0, action_url TEXT DEFAULT '', created_at INTEGER NOT NULL)")
        underlayer_db::exec_sql(db, &raw sql_notif)
        var idx_notif_learner = string("CREATE INDEX IF NOT EXISTS idx_notif_learner ON notifications(learner_id)")
        underlayer_db::exec_sql(db, &raw idx_notif_learner)
        var idx_notif_read = string("CREATE INDEX IF NOT EXISTS idx_notif_read ON notifications(learner_id, is_read)")
        underlayer_db::exec_sql(db, &raw idx_notif_read)
        // Content feedback table
        var sql_fb = string("CREATE TABLE IF NOT EXISTS content_feedback (id TEXT PRIMARY KEY, learner_id TEXT NOT NULL, concept_id TEXT NOT NULL, course_id TEXT DEFAULT '', feedback_type TEXT NOT NULL, message TEXT NOT NULL, page_url TEXT DEFAULT '', status TEXT DEFAULT 'pending', admin_notes TEXT DEFAULT '', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)")
        underlayer_db::exec_sql(db, &raw sql_fb)
        var idx_fb_concept = string("CREATE INDEX IF NOT EXISTS idx_fb_concept ON content_feedback(concept_id)")
        underlayer_db::exec_sql(db, &raw idx_fb_concept)
        var idx_fb_status = string("CREATE INDEX IF NOT EXISTS idx_fb_status ON content_feedback(status)")
        underlayer_db::exec_sql(db, &raw idx_fb_status)
        // Exercise reports table
        var sql_er = string("CREATE TABLE IF NOT EXISTS exercise_reports (id TEXT PRIMARY KEY, learner_id TEXT NOT NULL, exercise_id TEXT NOT NULL, concept_id TEXT NOT NULL, report_type TEXT NOT NULL, message TEXT NOT NULL, status TEXT DEFAULT 'pending', created_at INTEGER NOT NULL)")
        underlayer_db::exec_sql(db, &raw sql_er)
        var idx_er_exercise = string("CREATE INDEX IF NOT EXISTS idx_er_exercise ON exercise_reports(exercise_id)")
        underlayer_db::exec_sql(db, &raw idx_er_exercise)
        var idx_er_status = string("CREATE INDEX IF NOT EXISTS idx_er_status ON exercise_reports(status)")
        underlayer_db::exec_sql(db, &raw idx_er_status)
        // Prerequisites table
        var sql_prereq = string("CREATE TABLE IF NOT EXISTS course_prerequisites (course_id TEXT NOT NULL, required_course_id TEXT NOT NULL, min_mastery_pct INTEGER DEFAULT 80, PRIMARY KEY (course_id, required_course_id))")
        underlayer_db::exec_sql(db, &raw sql_prereq)
        var idx_prereq = string("CREATE INDEX IF NOT EXISTS idx_prereq_course ON course_prerequisites(course_id)")
        underlayer_db::exec_sql(db, &raw idx_prereq)
        // Skill assessments table
        var sql_assess = string("CREATE TABLE IF NOT EXISTS skill_assessments (id INTEGER PRIMARY KEY AUTOINCREMENT, learner_id TEXT NOT NULL, course_id TEXT NOT NULL, score INTEGER DEFAULT 0, total INTEGER DEFAULT 0, placement TEXT DEFAULT 'beginner', recommended_start TEXT DEFAULT '', created_at INTEGER NOT NULL)")
        underlayer_db::exec_sql(db, &raw sql_assess)
        var idx_assess = string("CREATE INDEX IF NOT EXISTS idx_assess_learner ON skill_assessments(learner_id)")
        underlayer_db::exec_sql(db, &raw idx_assess)
        // Bookmarks table
        var sql_bm = string("CREATE TABLE IF NOT EXISTS bookmarks (id TEXT PRIMARY KEY, learner_id TEXT NOT NULL, concept_id TEXT NOT NULL, course_id TEXT NOT NULL, note TEXT DEFAULT '', created_at INTEGER NOT NULL)")
        underlayer_db::exec_sql(db, &raw sql_bm)
        var idx_bm_learner = string("CREATE INDEX IF NOT EXISTS idx_bm_learner ON bookmarks(learner_id)")
        underlayer_db::exec_sql(db, &raw idx_bm_learner)
        var idx_bm_concept = string("CREATE INDEX IF NOT EXISTS idx_bm_concept ON bookmarks(learner_id, concept_id)")
        underlayer_db::exec_sql(db, &raw idx_bm_concept)
        // Certificates table
        var sql_cert = string("CREATE TABLE IF NOT EXISTS certificates (id TEXT PRIMARY KEY, learner_id TEXT NOT NULL, course_id TEXT NOT NULL, learner_name TEXT NOT NULL, course_title TEXT NOT NULL, completion_date TEXT NOT NULL, certificate_url TEXT DEFAULT '', created_at INTEGER NOT NULL)")
        underlayer_db::exec_sql(db, &raw sql_cert)
        var idx_cert_learner = string("CREATE INDEX IF NOT EXISTS idx_cert_learner ON certificates(learner_id)")
        underlayer_db::exec_sql(db, &raw idx_cert_learner)
        // Notes table
        var sql_notes = string("CREATE TABLE IF NOT EXISTS learner_notes (id TEXT PRIMARY KEY, learner_id TEXT NOT NULL, concept_id TEXT NOT NULL, course_id TEXT NOT NULL, content TEXT NOT NULL, section_ref TEXT DEFAULT '', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)")
        underlayer_db::exec_sql(db, &raw sql_notes)
        var idx_notes_learner = string("CREATE INDEX IF NOT EXISTS idx_notes_learner ON learner_notes(learner_id)")
        underlayer_db::exec_sql(db, &raw idx_notes_learner)
        var idx_notes_concept = string("CREATE INDEX IF NOT EXISTS idx_notes_concept ON learner_notes(learner_id, concept_id)")
        underlayer_db::exec_sql(db, &raw idx_notes_concept)
        // Achievements table
        var sql_ach = string("CREATE TABLE IF NOT EXISTS achievements (id TEXT PRIMARY KEY, learner_id TEXT NOT NULL, badge_type TEXT NOT NULL, badge_name TEXT NOT NULL, description TEXT NOT NULL, icon TEXT DEFAULT '', earned_at INTEGER NOT NULL)")
        underlayer_db::exec_sql(db, &raw sql_ach)
        var idx_ach_learner = string("CREATE INDEX IF NOT EXISTS idx_ach_learner ON achievements(learner_id)")
        underlayer_db::exec_sql(db, &raw idx_ach_learner)
        var idx_ach_type = string("CREATE INDEX IF NOT EXISTS idx_ach_type ON achievements(learner_id, badge_type)")
        underlayer_db::exec_sql(db, &raw idx_ach_type)
        // Course reviews table
        var sql_cr = string("CREATE TABLE IF NOT EXISTS course_reviews (id TEXT PRIMARY KEY, learner_id TEXT NOT NULL, course_id TEXT NOT NULL, rating INTEGER NOT NULL, title TEXT DEFAULT '', review_text TEXT DEFAULT '', helpful_count INTEGER DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)")
        underlayer_db::exec_sql(db, &raw sql_cr)
        var idx_cr_course = string("CREATE INDEX IF NOT EXISTS idx_cr_course ON course_reviews(course_id)")
        underlayer_db::exec_sql(db, &raw idx_cr_course)
        var idx_cr_learner = string("CREATE INDEX IF NOT EXISTS idx_cr_learner ON course_reviews(learner_id, course_id)")
        underlayer_db::exec_sql(db, &raw idx_cr_learner)
        // Streaks table
        var sql_streak = string("CREATE TABLE IF NOT EXISTS learning_streaks (learner_id TEXT PRIMARY KEY, current_streak INTEGER DEFAULT 0, longest_streak INTEGER DEFAULT 0, total_active_days INTEGER DEFAULT 0, last_active_date TEXT DEFAULT '')")
        underlayer_db::exec_sql(db, &raw sql_streak)
        // Daily activity log
        var sql_daily = string("CREATE TABLE IF NOT EXISTS daily_activity (learner_id TEXT NOT NULL, activity_date TEXT NOT NULL, sessions_count INTEGER DEFAULT 0, PRIMARY KEY (learner_id, activity_date))")
        underlayer_db::exec_sql(db, &raw sql_daily)
        // Study plans table
        var sql_sp = string("CREATE TABLE IF NOT EXISTS study_plans (id TEXT PRIMARY KEY, learner_id TEXT NOT NULL, course_id TEXT NOT NULL, plan_date TEXT NOT NULL, start_hour INTEGER DEFAULT 0, duration_minutes INTEGER DEFAULT 30, focus_concepts TEXT DEFAULT '', status TEXT DEFAULT 'planned', created_at INTEGER NOT NULL)")
        underlayer_db::exec_sql(db, &raw sql_sp)
        var idx_sp_learner = string("CREATE INDEX IF NOT EXISTS idx_sp_learner ON study_plans(learner_id)")
        underlayer_db::exec_sql(db, &raw idx_sp_learner)
        var idx_sp_date = string("CREATE INDEX IF NOT EXISTS idx_sp_date ON study_plans(learner_id, plan_date)")
        underlayer_db::exec_sql(db, &raw idx_sp_date)
    }

}
