#!/bin/sh
# build_samples.sh -- assemble the corpus, probe the opcode maps, build
# x86dec, run it, and cross-check the result.
#
#   ./build_samples.sh            build, run, cross-check
#   ./build_samples.sh --quick    fewer iterations
#
# The cross-check runs against a FRESH run, not against the committed
# x86dec.out, so that "the claims still hold on this machine today" is a
# statement about the machine and not a tautology about a checked-in file.
#
# Four things are produced here and x86dec reads all four:
#
#   corpus.txt     every labelled instruction from corpus.s, with the BYTES
#                  the assembler emitted and objdump's own reading of them.
#                  objdump is reader 1; x86dec's decoder is reader 2.
#   corpus_c.txt   the same for corpus.c, which is a COMPILER's output rather
#                  than a human's, so that the claim "gcc reached for this
#                  mnemonic" is a claim about bytes and can be checked.
#   maps.txt       the SAME 256 slots of each of the 0F, 0F 38 and 0F 3A maps
#                  read twice -- once as a legacy escape and once with a
#                  three-byte VEX in front -- so that there are two columns
#                  and the difference between them is the prefix's value.
#   scale3.txt     whatever `as` says about `lea 0(%rdi,%rsi,3), %rax`.  The
#                  artifact prints the refusal as evidence, so the evidence
#                  is captured by the script rather than typed into it.
#
# NOTE ON THE HAND-BUILT EVEX BYTES: this machine has no AVX-512, so no
# assembler here will emit one and none of the EVEX rows in the corpus come
# from as.  x86dec builds those bytes itself and hands them to objdump, which
# decodes encodings the CPU cannot run.  That is a deliberate third reader and
# the concept page explains why it matters.
set -e
cd "$(dirname "$0")"

CC=${CC:-cc}
CFLAGS=${CFLAGS:--O2 -Wall -Wextra}
OBJDUMP=${OBJDUMP:-objdump}

echo "==> toolchain"
$CC --version | head -1
$OBJDUMP --version | head -1
as --version | head -1

# ------------------------------------------------------------------
# 1. the human corpus
# ------------------------------------------------------------------
echo "==> assembling corpus.s"
as -o corpus.o corpus.s
$OBJDUMP -d -M intel corpus.o > corpus_objdump.txt

cat > _mkcorpus.py <<'PYEOF'
import re
lines = open('corpus_objdump.txt', errors='replace').read().splitlines()
rows, cur = [], None
for ln in lines:
    m = re.match(r'^[0-9a-f]+ <([^>]+)>:$', ln)
    if m:
        cur = m.group(1)
        continue
    m = re.match(r'^\s+([0-9a-f]+):\t([0-9a-f ]+?)\t+(.*)$', ln)
    if m and cur:
        rows.append((cur, m.group(2).split(), m.group(3).strip()))
        cur = None
src = {}
for ln in open('corpus.s', errors='replace'):
    m = re.match(r'^(\w+):\s+(.*)$', ln.strip())
    if m:
        src[m.group(1)] = m.group(2).strip()
out = ['# x86asm corpus -- GENERATED by build_samples.sh, do not hand-edit.',
       '# <label> | <bytes the assembler emitted> | <objdump Intel> | <AT&T source>']
n = 0
for label, by, dis in rows:
    out.append('%-20s | %-22s | %-34s | %s'
               % (label, ' '.join(by), dis, src.get(label, '')))
    n += 1
open('corpus.txt', 'w').write('\n'.join(out) + '\n')
print('    %d instructions, %d bytes total' % (n, sum(len(r[1]) for r in rows)))
PYEOF
python3 _mkcorpus.py

# ------------------------------------------------------------------
# 2. the compiler corpus
# ------------------------------------------------------------------
echo "==> compiling corpus.c with $CC $CFLAGS"
$CC $CFLAGS -c -o corpus_c.o corpus.c
$OBJDUMP -d -M intel corpus_c.o > corpus_c_objdump.txt

cat > _mkcorpusc.py <<'PYEOF'
import re
text = open('corpus_c_objdump.txt', errors='replace').read().splitlines()
out = ['# x86asm COMPILER corpus -- GENERATED by build_samples.sh.',
       '# <function> | <bytes gcc emitted> | <objdump Intel>',
       '# A claim about what a compiler did is a claim about bytes.']
cur, n = None, 0
for ln in text:
    m = re.match(r'^[0-9a-f]+ <([^>]+)>:$', ln)
    if m:
        cur = m.group(1)
        continue
    m = re.match(r'^\s+([0-9a-f]+):\t([0-9a-f ]+?)\t+(.*)$', ln)
    if m and cur:
        out.append('%-20s | %-22s | %s' % (cur, ' '.join(m.group(2).split()), m.group(3).strip()))
        cur = None
        n += 1
    elif ln.strip() == '':
        cur = None
open('corpus_c.txt', 'w').write('\n'.join(out) + '\n')
print('    %d instructions of compiler-chosen code' % n)
PYEOF
python3 _mkcorpusc.py

# ------------------------------------------------------------------
# 3. the opcode map probe, read twice
#
# One candidate opcode per file, so a slot with a ModRM byte cannot eat the
# next slot's bytes, and one objdump invocation per column.
# ------------------------------------------------------------------
echo "==> probing the 0F, 0F 38 and 0F 3A maps twice (768 legacy, 768 VEX)"
rm -rf mapbin vexbin && mkdir mapbin vexbin
cat > _mkbin.py <<'PYEOF'
specs = {'0F': [0x0F], '0F38': [0x0F, 0x38], '0F3A': [0x0F, 0x3A]}
for name, pre in specs.items():
    for op in range(256):
        with open('mapbin/%s_%02x.bin' % (name, op), 'wb') as f:
            f.write(bytes(pre + [op]) + b'\x90' * 13)
# The same 768 slots again, with a three-byte VEX in FRONT of the same map
# escape.  VEX byte 1 is R X B mmmmm, so 0xE1 / 0xE2 / 0xEE select the
# 0f / 0f 38 / 0f 3a maps and nothing else about the probe changes.  Two
# columns, one byte, and the difference between them is the prefix's value.
vex = {'0F': 0xE1, '0F38': 0xE2, '0F3A': 0xE3}
for name, p1 in vex.items():
    for op in range(256):
        with open('vexbin/%s_%02x.bin' % (name, op), 'wb') as f:
            f.write(bytes([0xC4, p1, 0x79, op]) + b'\x90' * 12)
PYEOF
python3 _mkbin.py
$OBJDUMP -D -b binary -m i386:x86-64 -M intel mapbin/*.bin > maps_raw.txt
$OBJDUMP -D -b binary -m i386:x86-64 -M intel vexbin/*.bin > maps_vex_raw.txt

cat > _mkmaps.py <<'PYEOF'
import re

def read(path):
    verdict, cur = {}, None
    for ln in open(path, errors='replace').read().splitlines():
        if re.match(r'^\S+\.bin:\s+file format binary', ln):
            m = re.search(r'/(\w+)_([0-9a-f]{2})\.bin$', ln.split(':')[0])
            cur = (m.group(1), int(m.group(2), 16)) if m else None
            continue
        m = re.match(r'^\s+([0-9a-f]+):\t([0-9a-f ]+?)\t+(.*)$', ln)
        if m and cur and int(m.group(1), 16) == 0:
            verdict[cur] = m.group(3).strip()
            cur = None
    return verdict

leg, vx = read('maps_raw.txt'), read('maps_vex_raw.txt')
out = ['# x86asm opcode map probe -- GENERATED by build_samples.sh.',
       '# <map> <opcode byte in hex> | <legacy reading> | <VEX reading>',
       '# "(bad)" means binutils does not name this slot.  That is a fact about',
       '# binutils and not a claim about what the ISA defines.  The two columns',
       '# are the SAME 256 slots read with and without a VEX prefix in front.']
ok = lambda v: '(bad)' not in v and 'no line' not in v
nl = nv = nb = 0
for name in ('0F', '0F38', '0F3A'):
    for op in range(256):
        a = leg.get((name, op), '(no line)')
        b = vx.get((name, op), '(no line)')
        nl += ok(a); nv += ok(b)
        if not (ok(a) or ok(b)):
            nb += 1
        out.append('%s %02x | %s | %s' % (name, op, a, b))
open('maps.txt', 'w').write('\n'.join(out) + '\n')
print('    %d slots probed twice: %d named legacy, %d named under VEX, '
      '%d named in at least one column, %d in neither'
      % (nl + nv + nb, nl, nv, nl + nv - nb, nb))
PYEOF
python3 _mkmaps.py

# ------------------------------------------------------------------
# 4. the assembler's own refusals, captured rather than quoted
# ------------------------------------------------------------------
echo "==> capturing the assembler's diagnostic for a x3 SIB scale"
cat > _probe.s <<'SPEOF'
.text
probe:  lea 0(%rdi,%rsi,3), %rax
SPEOF
as -o _probe.o _probe.s 2>&1 | grep "Error" > scale3.txt || true
if [ -s scale3.txt ]; then echo "    $(cat scale3.txt)"; else echo "    (the assembler ACCEPTED it)"; fi

# ------------------------------------------------------------------
# 5. build and run the artifact
# ------------------------------------------------------------------
echo "==> building x86dec with: $CC $CFLAGS"
$CC $CFLAGS -o x86dec x86dec.c -lm

if [ "$1" = "--quick" ]; then
    echo "==> quick run"
    OUT=/tmp/x86dec.quick.$$
    ./x86dec --quick > "$OUT"
else
    echo "==> running x86dec"
    OUT=x86dec.out
    ./x86dec > "$OUT"
fi

echo "==> cross-checking $OUT"
python3 crosscheck.py "$OUT"
rc=$?

if [ "$1" != "--quick" ]; then
    echo
    echo "==> the four results, on their own, because a harness that can only be"
    echo "    read inside a transcript is a harness nobody reads."
    echo
    sed -n '/THE RATIOS THAT ARE THE POINT/,/^$/p'   "$OUT" | sed 's/^/  ALU /'
    sed -n '/cmp + xor + setl/,/^$/p'               "$OUT" | sed 's/^/  FLG /'
    sed -n '/vaddps xmm2, xmm0, xmm1/,/^$/p'       "$OUT" | sed 's/^/  VEX /'
    sed -n '/IT READ IT/,+3p'                       "$OUT" | sed 's/^/  CGV /'
    sed -n '/^  0F  /p;/^  0F38/p;/^  0F3A/p'       "$OUT" | sed 's/^/  MAP /'
fi

rm -f _mkcorpus.py _mkcorpusc.py _mkbin.py _mkmaps.py _probe.s _probe.o
exit $rc
