#!/bin/sh
# build_samples.sh -- the x86sys course: build every input, run the artifact
# three times, and cross-check a FRESH run rather than the committed one.
#
#   ./build_samples.sh            build, run three times, cross-check
#   ./build_samples.sh --quick    fewer iterations in the timing section
#
# The cross-check runs against a FRESH run, not against the committed
# sysdump.out, so that "the claims still hold on this machine today" is a
# statement about the machine and not a tautology about a checked-in file.
#
# THREE THINGS ARE PRODUCED HERE, and sysdump.c reads one of them:
#
#   sysdump_dis.txt   objdump of ONE function -- the naive C form of the
#                     16-byte read in the canonical sweep.  It exists only to
#                     be disassembled, and the disassembly is what turned a
#                     wrong number into a retraction: the sweep reported an
#                     ALIGNMENT rule because gcc had compiled the load to
#                     `movdqa`.  A retraction with the instruction beside it is
#                     worth more than a retraction with the word `movdqa` in
#                     it, and this file is how the instruction gets there.
#   sysdump.out       the artifact's own output, which is what ships.
#   run1.txt run2.txt two more runs, so that a reader can see which numbers
#                     move between runs and which do not.
set -e
cd "$(dirname "$0")"

CC=${CC:-cc}
CFLAGS=${CFLAGS:--O2 -Wall -Wextra}
OBJDUMP=${OBJDUMP:-objdump}

echo "==> toolchain"
$CC --version | head -1
$OBJDUMP --version | head -1

# ------------------------------------------------------------------
# 1. the disassembly that the retraction depends on
# ------------------------------------------------------------------
echo "==> sysdump_dis.txt"
{
  echo "# sysdump_dis.txt -- GENERATED by build_samples.sh.  Do not hand-edit."
  echo "# The disassembly of the NAIVE C form of the 16-byte read used in the"
  echo "# canonical sweep of section 5.  Section 5 also prints the inline"
  echo "# movdqu it uses INSTEAD, so this file is the evidence and not the"
  echo "# source of the number."
  $OBJDUMP -d --no-show-raw-insn sysdump 2>/dev/null \
    | sed -n '/<sysdump_rd16_naive>:/,/^$/p' \
    | sed 's/^/  /'
} > sysdump_dis.txt
sed -n '4,12p' sysdump_dis.txt | sed 's/^/    /'

# ------------------------------------------------------------------
# 2. build and run
# ------------------------------------------------------------------
echo "==> building sysdump with: $CC $CFLAGS"
$CC $CFLAGS -o sysdump sysdump.c

if [ "$1" = "--quick" ]; then
    echo "==> quick run"
    ./sysdump --quick > /tmp/opencode/sysdump.quick.$$
else
    echo "==> run 1"
    ./sysdump > sysdump.out
    echo "==> run 2"
    ./sysdump > run1.txt
    echo "==> run 3"
    ./sysdump > run2.txt
fi

# ------------------------------------------------------------------
# 3. cross-check a fresh run
# ------------------------------------------------------------------
echo "==> cross-checking a FRESH run"
./sysdump ${1:---full} > /tmp/opencode/sysdump.fresh.$$
python3 crosscheck.py /tmp/opencode/sysdump.fresh.$$
rc=$?

if [ "$1" != "--quick" ]; then
    echo
    echo "==> the results, on their own, because a harness that can only be read"
    echo "    inside a transcript is a harness nobody reads."
    echo
    sed -n '/^3\.  THE BOUNDARY/,/^  EDGE | rows/p'  sysdump.out | sed 's/^/  EDG /'
    sed -n '/^4\.  THE EXCEPTIONS/,/^  RAISE |/p'      sysdump.out | sed 's/^/  EXC /'
    sed -n '/^  BISE | width/,/^  BISE | first/p'       sysdump.out | sed 's/^/  CAN /'
    sed -n '/^6A\./,/^  6B\./p'                          sysdump.out | sed 's/^/  AB1 /'
    sed -n '/^6B\./,/^  6C\./p'                          sysdump.out | sed 's/^/  AB2 /'
    sed -n '/^  PAGEMAP | a fresh/,/^  PAGEMAP | the same/p' sysdump.out | sed 's/^/  PMG /'
    sed -n '/^   R1\./,/^  LIMITS/p'                    sysdump.out | sed 's/^/  RETR/'
fi
exit $rc
