// HAT course - Analytical drill question bank.
// GENERATED by tools/hat_drill_extract.py from
// content/src/hat_analytical_drill.ch - do not hand-edit.
//
// The text and the answer key are lifted from the printed
// paper in the lesson, so the timed runner and the answer
// key can never disagree.
//
// Shape: { q, o, a, e }
//   q  question text
//   o  options in order
//   a  index of the correct option
//   e  why that option is right and the trap is wrong
public namespace underlayer_content {

    public func render_hat_analytical_drill_bank(page : &mut HtmlPage) {
        #js {
            var HAT_ANALYTICAL_DRILL_BANK = [
                { q: "Who sits in seat 2?", o: ["B", "E", "C", "D"], a: 1, e: "The only arrangement is A, E, C, D, B: C is middle, A is leftmost, D is immediately right of C, and E is not at an end, so E takes seat 2 and B seat 5" },
                { q: "Who sits at the extreme right?", o: ["B", "D", "E", "A"], a: 0, e: "Seat 5 is the extreme right in A, E, C, D, B" },
                { q: "Who sits immediately to the left of D?", o: ["A", "C", "E", "B"], a: 1, e: "D is in seat 4 and C in seat 3, so C is immediately to its left" },
                { q: "Which talk is held on Monday?", o: ["T1", "T3", "T4", "cannot be determined"], a: 1, e: "T2 is fixed on Tuesday. T1 cannot be Monday, and T4 must come after T3, so T3 is forced onto Monday in every valid arrangement" },
                { q: "Which talk is held on Wednesday?", o: ["T1", "T4", "T3", "cannot be determined"], a: 3, e: "The two valid arrangements are T3, T2, T1, T4 and T3, T2, T4, T1, so Wednesday is T1 in one and T4 in the other" },
                { q: "All poets are dreamers. No dreamers are practical. Which follows?", o: ["No poets are practical", "Some poets are practical", "All practical people are poets", "Nothing follows"], a: 0, e: "Poets sit inside dreamers, and the dreamers circle avoids practical things entirely, so no poet is practical" },
                { q: "Some birds cannot fly. All penguins are birds. Which follows?", o: ["Some penguins cannot fly", "All penguins cannot fly", "No penguins can fly", "Nothing follows"], a: 3, e: "The flightless birds may all lie outside the penguin circle; the overlap between penguins and non-flying birds is not guaranteed" },
                { q: "A is the mother of B. B is the sister of C. C is the father of D. How is A related to D?", o: ["Mother", "Aunt", "Grandmother", "Sister"], a: 2, e: "A is a parent of B, B and C are siblings so A is also C's parent, and C is D's father" },
                { q: "P is the brother of Q. Q is the wife of R. R is the father of S. How is P related to S?", o: ["Father", "Maternal uncle", "Brother", "Cousin"], a: 1, e: "Q is S's mother through R, and P is Q's brother, which makes P S's uncle on the mother's side" },
                { q: "A man walks 6 km south, then turns and walks 8 km east. How far is he from his starting point?", o: ["2 km", "10 km", "14 km", "48 km"], a: 1, e: "6 km south and 8 km east form a 6-8-10 triangle; adding the legs gives the wrong 14 km" },
                { q: "A woman starts facing north, turns right twice and then left once. Which direction is she facing?", o: ["North", "South", "East", "West"], a: 2, e: "North to east to south, then a left turn from south leads to east" },
                { q: "If CAT is coded as DBU, how is DOG coded?", o: ["EPH", "CNG", "EPI", "FQI"], a: 0, e: "Every letter shifts one place forward: D to E, O to P, G to H" },
                { q: "If MOTHER is coded as REHTOM, how is FATHER coded?", o: ["GBUIFS", "REHTAF", "RETHAF", "FATHEE"], a: 1, e: "The code reverses the word, so FATHER becomes REHTAF" },
                { q: "What comes next: 2, 5, 10, 17, 26, ?", o: ["35", "37", "39", "40"], a: 1, e: "Differences are 3, 5, 7, 9 and then 11, so 26 + 11 = 37" },
                { q: "What comes next: 3, 6, 12, 24, ?", o: ["30", "36", "48", "96"], a: 2, e: "Each term doubles, so the next is 48; option 96 is the term after that" },
                { q: "What comes next: A, C, F, J, ?", o: ["M", "N", "O", "P"], a: 2, e: "Letter gaps increase by one each time: plus 2, plus 3, plus 4, then plus 5 places from J gives O" },
                { q: "Enrolment rises from 300 to 350 students. What is the percentage increase?", o: ["14.3 percent", "16.7 percent", "25 percent", "50 percent"], a: 1, e: "50 divided by the original 300; dividing by 350 gives the trap answer 14.3 percent" },
                { q: "Department A grows from 120 to 150 staff; department B from 80 to 100. Which grew faster in percentage terms?", o: ["A", "B", "the same rate", "cannot be determined from the totals"], a: 2, e: "A grew 30 on 120 and B grew 20 on 80; both are 25 percent, so the smaller absolute rise is the same percentage" },
                { q: "What is the value of x? (1) x + y = 10 (2) y = 4", o: ["", "", "both together, neither alone", "neither, even together"], a: 2, e: "(1) leaves x dependent on y and (2) says nothing about x; together x = 6" },
                { q: "Is n an even number? (1) n is a multiple of 6 (2) n is greater than 10", o: ["", "", "both together, neither alone", "neither, even together"], a: 0, e: "Every multiple of 6 is even, so the question is answered; being greater than 10 says nothing about parity" }
            ];
        }
    }

}
