// HAT course — baseline diagnostic question bank.
//
// The full HAT-1 shape: 40 quantitative, 30 verbal and 30 analytical
// questions, one mark each, 100 marks total, no negative marking. The bank is
// emitted as plain JS data because #html blocks cannot contain loops
// (docs/implementation-gaps.md); the runner in hat_diagnostic_runner.ch renders
// it client-side and scores it. Every question was checked by hand and has a
// single unambiguous key.
//
// Macro notes: percentages are spelled "percent" because a bare % is a format
// token in #js; no double quotes, no grouping parentheses, no regex literals.
public namespace underlayer_content {

using std::string

    public func render_hat_diagnostic_bank(page : &mut HtmlPage) {
        #js {
            var HAT_DIAG_QUANT = [
                { q: "What is 15 percent of 240?", o: ["24", "36", "45", "16"], a: 1, e: "10 percent is 24 and 5 percent is 12, so 15 percent is 36." },
                { q: "A price rises from Rs 80 to Rs 100. What is the percentage increase?", o: ["20 percent", "25 percent", "80 percent", "12.5 percent"], a: 1, e: "The change is 20 on an original of 80, so 20 divided by 80 is 25 percent." },
                { q: "What is the mean of 4, 8, 10 and 14?", o: ["8", "9", "12", "36"], a: 1, e: "The total is 36 over 4 values, so the mean is 9." },
                { q: "Solve for x: 3x + 7 = 22.", o: ["3", "5", "15", "9.67"], a: 1, e: "Subtract 7 to get 3x = 15, so x = 5." },
                { q: "What is the simple interest on Rs 2,000 at 5 percent per year for 3 years?", o: ["Rs 100", "Rs 300", "Rs 3,000", "Rs 30"], a: 1, e: "Simple interest is 2,000 x 5 percent x 3, which is Rs 300." },
                { q: "Divide Rs 180 in the ratio 2 : 3 : 4. What is the largest share?", o: ["Rs 40", "Rs 60", "Rs 80", "Rs 90"], a: 2, e: "The total is 9 parts, so one part is Rs 20 and the largest share is 4 parts, Rs 80." },
                { q: "What is the LCM of 12 and 18?", o: ["6", "36", "72", "216"], a: 1, e: "12 = 2x2x3 and 18 = 2x3x3, so the LCM is 2x2x3x3 = 36." },
                { q: "What is the HCF of 24 and 36?", o: ["6", "12", "18", "72"], a: 1, e: "24 = 2x2x2x3 and 36 = 2x2x3x3, so the common factor is 2x2x3 = 12." },
                { q: "Which of these numbers is divisible by 9?", o: ["4527", "4528", "4526", "4531"], a: 0, e: "A number is divisible by 9 when its digits sum to a multiple of 9. Here 4+5+2+7 = 18." },
                { q: "What is 2 raised to the power 5, multiplied by 2 raised to the power 3?", o: ["64", "256", "128", "512"], a: 1, e: "Add the exponents to get 2 to the power 8, which is 256." },
                { q: "What is the square root of 144?", o: ["11", "12", "13", "14"], a: 1, e: "12 x 12 = 144." },
                { q: "If 3x - 7 = 11, what is x?", o: ["6", "4", "18", "9"], a: 0, e: "Add 7 to get 3x = 18, so x = 6." },
                { q: "If x = 5, what is the value of (x + 3)(x - 3)?", o: ["16", "22", "34", "64"], a: 0, e: "The product is 8 x 2 = 16, which also equals x squared minus 9." },
                { q: "What is the sum of the roots of x squared - 5x + 6 = 0?", o: ["5", "6", "-5", "1"], a: 0, e: "The equation factors as (x - 2)(x - 3), so the roots 2 and 3 sum to 5." },
                { q: "The sequence 3, 7, 11, ... increases by 4 each term. What is the 10th term?", o: ["39", "43", "36", "40"], a: 0, e: "The 10th term is 3 + 9 x 4 = 39." },
                { q: "The sequence 2, 6, 18, ... multiplies by 3 each term. What is the 5th term?", o: ["54", "162", "486", "108"], a: 1, e: "2 x 3 x 3 x 3 x 3 = 162." },
                { q: "Two angles of a triangle are 50 and 60 degrees. What is the third angle?", o: ["70", "60", "80", "90"], a: 0, e: "The angles of a triangle sum to 180, and 180 - 110 = 70." },
                { q: "Using pi = 22/7, what is the area of a circle of radius 7 cm?", o: ["154 cm squared", "44 cm squared", "49 cm squared", "22 cm squared"], a: 0, e: "Area = pi x r x r = 22/7 x 49 = 154." },
                { q: "A rectangle is 12 cm by 5 cm. What is the length of its diagonal?", o: ["13 cm", "17 cm", "60 cm", "11 cm"], a: 0, e: "By Pythagoras the diagonal is the square root of 144 + 25 = 169, which is 13." },
                { q: "What is the distance between the points (0, 0) and (3, 4)?", o: ["5", "7", "12", "25"], a: 0, e: "The distance is the square root of 9 + 16 = 25, which is 5." },
                { q: "What is the slope of the line through (1, 2) and (3, 8)?", o: ["3", "2", "6", "1"], a: 0, e: "Slope is change in y over change in x, so 6 divided by 2 = 3." },
                { q: "A fair six-sided die is rolled once. What is the probability of an even number?", o: ["1/6", "1/3", "1/2", "2/3"], a: 2, e: "The even faces are 2, 4 and 6, so the probability is 3/6 = 1/2." },
                { q: "In how many different orders can the letters A, B and C be arranged?", o: ["3", "6", "9", "27"], a: 1, e: "There are 3 x 2 x 1 = 6 arrangements." },
                { q: "Two fair coins are tossed. What is the probability that both show heads?", o: ["1/2", "1/3", "1/4", "3/4"], a: 2, e: "The four equally likely outcomes are HH, HT, TH and TT, so the probability is 1/4." },
                { q: "What is the median of 3, 9, 1, 7 and 5?", o: ["3", "5", "7", "9"], a: 1, e: "Sorted, the values are 1, 3, 5, 7, 9, so the middle value is 5." },
                { q: "If 3 pens cost Rs 45, what do 7 pens cost at the same rate?", o: ["Rs 105", "Rs 90", "Rs 135", "Rs 120"], a: 0, e: "One pen costs Rs 15, so 7 pens cost Rs 105." },
                { q: "40 is what percent of 200?", o: ["20 percent", "25 percent", "40 percent", "5 percent"], a: 0, e: "40 divided by 200 is 0.2, which is 20 percent." },
                { q: "Four workers build a wall in 12 days. How long will six workers take at the same rate?", o: ["8 days", "9 days", "18 days", "24 days"], a: 0, e: "The job is 48 worker-days, and 48 divided by 6 = 8 days." },
                { q: "What is 2/5 as a percentage?", o: ["25 percent", "40 percent", "20 percent", "50 percent"], a: 1, e: "2/5 = 0.4 = 40 percent." },
                { q: "A car travels at 60 km/h for 2 hours and then at 40 km/h for 3 hours. What is its average speed?", o: ["48 km/h", "50 km/h", "45 km/h", "52 km/h"], a: 0, e: "Total distance 120 + 120 = 240 km over 5 hours gives 48 km/h." },
                { q: "The sum of two consecutive integers is 45. What is the smaller integer?", o: ["22", "23", "21", "24"], a: 0, e: "The integers are 22 and 23, so the smaller is 22." },
                { q: "A square has an area of 49 cm squared. What is its perimeter?", o: ["28 cm", "49 cm", "14 cm", "21 cm"], a: 0, e: "The side is 7 cm, so the perimeter is 4 x 7 = 28 cm." },
                { q: "What is 0.1 + 0.2?", o: ["0.3", "0.12", "0.03", "0.29"], a: 0, e: "0.1 + 0.2 = 0.3." },
                { q: "A train covers 120 km in 1 hour 30 minutes. What is its average speed?", o: ["80 km/h", "90 km/h", "100 km/h", "60 km/h"], a: 0, e: "1 hour 30 minutes is 1.5 hours, and 120 divided by 1.5 = 80." },
                { q: "What is the compound interest on Rs 1,000 at 10 percent per year for 2 years?", o: ["Rs 200", "Rs 210", "Rs 220", "Rs 100"], a: 1, e: "The amount is 1,000 x 1.1 x 1.1 = 1,210, so the interest is Rs 210." },
                { q: "What is 25 percent of 80?", o: ["20", "25", "40", "15"], a: 0, e: "A quarter of 80 is 20." },
                { q: "If 5x = 45, what is x?", o: ["9", "5", "40", "225"], a: 0, e: "Divide both sides by 5 to get x = 9." },
                { q: "The average of five numbers is 12. What is their sum?", o: ["60", "17", "12", "50"], a: 0, e: "The sum is the average times the count, 12 x 5 = 60." },
                { q: "A dozen eggs cost Rs 240. What do 5 eggs cost at the same rate?", o: ["Rs 100", "Rs 120", "Rs 90", "Rs 96"], a: 0, e: "One egg costs Rs 20, so 5 eggs cost Rs 100." },
                { q: "Which of these values is the largest?", o: ["3/4", "0.7", "2/3", "0.65"], a: 0, e: "3/4 = 0.75, which is larger than 0.7, 2/3 (about 0.67) and 0.65." }
            ];

            var HAT_DIAG_VERBAL = [
                { q: "Choose the word closest in meaning to ABUNDANT.", o: ["Scarce", "Plentiful", "Hidden", "Weak"], a: 1, e: "Abundant means existing in large quantities, that is, plentiful." },
                { q: "Choose the word closest in meaning to CANDID.", o: ["Frank", "Shy", "Angry", "Silent"], a: 0, e: "Candid means honest and straightforward, that is, frank." },
                { q: "Choose the word most opposite in meaning to FRUGAL.", o: ["Wasteful", "Thrifty", "Careful", "Modest"], a: 0, e: "Frugal means economical, so its opposite is wasteful." },
                { q: "Choose the word most opposite in meaning to OBSCURE.", o: ["Unclear", "Well-known", "Hidden", "Difficult"], a: 1, e: "Obscure means little known, so its opposite is well-known." },
                { q: "Choose the word closest in meaning to METICULOUS.", o: ["Careless", "Careful", "Quick", "Rude"], a: 1, e: "Meticulous means showing great attention to detail, that is, careful." },
                { q: "Choose the word most opposite in meaning to TRANSPARENT.", o: ["Clear", "Opaque", "Honest", "Thin"], a: 1, e: "Transparent lets light through, so its opposite is opaque." },
                { q: "Choose the word closest in meaning to EPHEMERAL.", o: ["Eternal", "Short-lived", "Strong", "Ancient"], a: 1, e: "Ephemeral means lasting for a very short time." },
                { q: "Choose the word most opposite in meaning to BENEVOLENT.", o: ["Kind", "Cruel", "Generous", "Wealthy"], a: 1, e: "Benevolent means well-meaning and kind, so its opposite is cruel." },
                { q: "Choose the word closest in meaning to TENACIOUS.", o: ["Persistent", "Weak", "Loose", "Brief"], a: 0, e: "Tenacious means holding firmly, that is, persistent." },
                { q: "Choose the word closest in meaning to LUCID.", o: ["Clear", "Dark", "Loud", "Heavy"], a: 0, e: "Lucid means expressed clearly and easy to understand." },
                { q: "BOOK is to CHAPTER as BUILDING is to:", o: ["Floor", "Brick", "Tall", "City"], a: 0, e: "A chapter is a division of a book, just as a floor is a division of a building." },
                { q: "DOCTOR is to HOSPITAL as TEACHER is to:", o: ["School", "Student", "Book", "Lesson"], a: 0, e: "A doctor works in a hospital, and a teacher works in a school." },
                { q: "HOT is to COLD as UP is to:", o: ["Down", "Above", "Top", "High"], a: 0, e: "Hot and cold are opposites, so the opposite of up is down." },
                { q: "PEN is to WRITE as KNIFE is to:", o: ["Cut", "Sharp", "Metal", "Kitchen"], a: 0, e: "A pen is used to write, and a knife is used to cut." },
                { q: "AUTHOR is to NOVEL as COMPOSER is to:", o: ["Symphony", "Piano", "Music", "Concert"], a: 0, e: "An author creates a novel, and a composer creates a symphony." },
                { q: "Complete the sentence: The committee was ______ in its praise; not a single member had anything negative to say.", o: ["unanimous", "divided", "hesitant", "silent"], a: 0, e: "The clause after the semicolon shows complete agreement, so unanimous fits." },
                { q: "Complete the sentence: The evidence was so ______ that the jury reached a verdict within minutes.", o: ["compelling", "doubtful", "tedious", "scanty"], a: 0, e: "A verdict reached in minutes implies the evidence was convincing, that is, compelling." },
                { q: "Complete the sentence: She approached the problem with ______, refusing to give up after the first failure.", o: ["persistence", "panic", "indifference", "haste"], a: 0, e: "Refusing to give up describes persistence." },
                { q: "Complete the sentence: The argument was ______, because it assumed what it set out to prove.", o: ["circular", "sound", "detailed", "brief"], a: 0, e: "Assuming the conclusion is the definition of a circular argument." },
                { q: "Complete the sentence: Despite his ______ manner, he noticed every detail.", o: ["casual", "hostile", "formal", "generous"], a: 0, e: "The contrast word despite sets an offhand manner against close attention, so casual fits." },
                { q: "Choose the correct verb: Neither of the boys ______ finished the assignment.", o: ["has", "have", "are", "were"], a: 0, e: "Neither is singular, so it takes the singular verb has." },
                { q: "Choose the correct verb: She is one of the best students who ______ ever studied here.", o: ["has", "have", "is", "was"], a: 1, e: "The relative clause describes students, which is plural, so have is correct." },
                { q: "Which sentence is grammatically correct?", o: ["Each of the players have a locker.", "Each of the players has a locker.", "Each of the players are having a locker.", "Each of the player has a locker."], a: 1, e: "Each is singular, so it takes has, while the noun after of stays plural." },
                { q: "Choose the correct word: He has been working here ______ 2010.", o: ["for", "since", "from", "during"], a: 1, e: "Since is used with a point in time, while for is used with a duration." },
                { q: "Choose the correct pronoun: Between you and ______, this is difficult.", o: ["I", "me", "myself", "mine"], a: 1, e: "A preposition such as between takes the object pronoun me." },
                { q: "What is the main idea of the passage?", p: "Bees do not simply gather nectar; they communicate. When a forager finds a rich source of food, she returns to the hive and performs a dance whose direction and duration encode the source's location and quality. Other workers interpret the dance and fly directly to the food, often without searching. The behaviour is remarkable because it passes on information about a place the other bees have never visited.", o: ["Bees use a dance to share information about food sources.", "Bees prefer nectar to pollen.", "Bees cannot find food on their own.", "Dances are used only during mating."], a: 0, e: "The passage explains how a dance communicates the location and quality of food." },
                { q: "According to the passage, what do the direction and duration of the dance together encode?", p: "Bees do not simply gather nectar; they communicate. When a forager finds a rich source of food, she returns to the hive and performs a dance whose direction and duration encode the source's location and quality. Other workers interpret the dance and fly directly to the food, often without searching. The behaviour is remarkable because it passes on information about a place the other bees have never visited.", o: ["The location and quality of the food source", "The age of the forager", "The size of the hive", "The colour of the flowers"], a: 0, e: "The passage says the direction and duration encode the source's location and quality." },
                { q: "What can be inferred about the other workers from the passage?", p: "Bees do not simply gather nectar; they communicate. When a forager finds a rich source of food, she returns to the hive and performs a dance whose direction and duration encode the source's location and quality. Other workers interpret the dance and fly directly to the food, often without searching. The behaviour is remarkable because it passes on information about a place the other bees have never visited.", o: ["They can reach the food without searching.", "They avoid the forager.", "They become foragers immediately.", "They cannot understand the dance."], a: 0, e: "The passage says they fly directly to the food, often without searching." },
                { q: "The city added bike lanes, and since then average commute times have risen. The conclusion that the lanes made traffic worse is weak mainly because:", o: ["It assumes the lanes caused the rise without ruling out other causes.", "It ignores the cost of the lanes.", "It relies on a very small sample.", "It attacks the planners rather than the plan."], a: 0, e: "Correlation is not causation, and other factors may explain the longer commutes." },
                { q: "The proposal, though presented with confidence, rests on assumptions its author never examines. The author's tone is:", o: ["Admiring", "Critical", "Neutral", "Humorous"], a: 1, e: "Pointing to unexamined assumptions and misplaced confidence is a critical stance." }
            ];

            var HAT_DIAG_ANALYTICAL = [
                { q: "All roses are flowers. All flowers need water. Which conclusion necessarily follows?", o: ["All roses need water.", "All flowers are roses.", "No flowers are roses.", "Some roses do not need water."], a: 0, e: "Whatever is true of all flowers is true of roses." },
                { q: "Some students are athletes. All athletes are healthy. Which conclusion necessarily follows?", o: ["Some students are healthy.", "All students are healthy.", "No students are healthy.", "All healthy people are students."], a: 0, e: "The student-athletes must be healthy, so some students are healthy." },
                { q: "No cats are reptiles. All reptiles are cold-blooded. Which conclusion follows?", o: ["All cold-blooded animals are reptiles.", "Some cold-blooded animals are not cats.", "No cold-blooded animals are cats.", "All cats are cold-blooded."], a: 1, e: "Reptiles are cold-blooded and are not cats, so some cold-blooded animals are not cats." },
                { q: "All engineers are graduates. Some graduates are managers. Which conclusion necessarily follows?", o: ["Some engineers are managers.", "Some managers are engineers.", "All managers are engineers.", "None of these follows."], a: 3, e: "The overlap between graduates and managers need not include any engineer." },
                { q: "Statement: To reduce road accidents, the city should lower the speed limit on all highways. The argument assumes that:", o: ["Lowering speed limits reduces accidents.", "Drivers will ignore the new limit.", "Highways have no accidents.", "Speed is the only cause of accidents."], a: 0, e: "The recommendation only works if lower limits actually reduce accidents." },
                { q: "Statement: Our advertisement increased sales, so advertising always works. The argument assumes that:", o: ["The sales rise was caused by the advertisement and not by other factors.", "Advertising is expensive.", "Sales never rise without advertising.", "All customers read advertisements."], a: 0, e: "It ignores other reasons why sales might have risen." },
                { q: "Statement: This medicine is safe because it is natural. The argument assumes that:", o: ["Natural substances are always safe.", "Medicines are expensive.", "Natural products are common.", "The medicine has no side effects."], a: 0, e: "The word natural does not by itself guarantee safety." },
                { q: "Statements: All squares are rectangles. All rectangles are quadrilaterals. Conclusions: I. All squares are quadrilaterals. II. All quadrilaterals are squares. Which conclusion follows?", o: ["Only I", "Only II", "Both I and II", "Neither I nor II"], a: 0, e: "I follows by chaining, while II reverses the relation and does not follow." },
                { q: "Statements: Some books are pens. No pen is a pencil. Conclusions: I. Some books are not pencils. II. All books are pencils. Which conclusion follows?", o: ["Only I", "Only II", "Both I and II", "Neither I nor II"], a: 0, e: "The books that are pens cannot be pencils, so I follows, while II is contradicted." },
                { q: "Statements: All flowers are trees. Some trees are leaves. Conclusions: I. Some flowers are leaves. II. Some leaves are trees. Which conclusion follows?", o: ["Only I", "Only II", "Both I and II", "Neither I nor II"], a: 1, e: "Some trees are leaves means some leaves are trees; the flowers need not touch the leaves." },
                { q: "Statement: Should mobile phones be banned in classrooms? Argument I: Yes, they distract students from learning. Argument II: No, phones are expensive. Which argument is strong?", o: ["Only I", "Only II", "Both I and II", "Neither I nor II"], a: 0, e: "Distraction is directly relevant, while the price of phones is not." },
                { q: "Statement: Should students take a gap year after school? Argument I: Yes, it lets them gain experience and maturity. Argument II: No, because everyone else goes straight to university. Which argument is strong?", o: ["Only I", "Only II", "Both I and II", "Neither I nor II"], a: 0, e: "The first gives a real benefit, while the second merely follows the crowd." },
                { q: "Statement: Should the legal drinking age be raised? Argument I: Yes, it may reduce alcohol-related accidents among the young. Argument II: No, because adults were once young too. Which argument is strong?", o: ["Only I", "Only II", "Both I and II", "Neither I nor II"], a: 0, e: "The first is relevant to the stated aim, while the second is irrelevant." },
                { q: "The road was icy. Many cars skidded. Which statement best describes the relation?", o: ["The icy road caused the skidding.", "The skidding caused the icy road.", "The two events are unrelated.", "Both are effects of a common cause."], a: 0, e: "Ice reduces friction and is the natural cause of the skidding." },
                { q: "A water pipe burst in the building. The basement flooded. Which statement best describes the relation?", o: ["The burst pipe caused the flooding.", "The flooding caused the pipe to burst.", "The two events are unrelated.", "Both are effects of a common cause."], a: 0, e: "Water from the burst pipe is the direct cause of the flood." },
                { q: "Since the new manager arrived, sales have risen. Therefore the manager caused the rise. This reasoning is weak because:", o: ["Other factors may explain the rise.", "Managers never affect sales.", "Sales always rise over time.", "The manager is new."], a: 0, e: "A coincidental sequence of events does not establish cause." },
                { q: "Problem: Many accidents occur at a particular intersection. Which is the most reasonable course of action?", o: ["Install traffic signals and clearer signs there.", "Ban all vehicles from the city.", "Ignore it, since accidents are inevitable.", "Fine every driver who passes through."], a: 0, e: "The action should address the specific cause at that location." },
                { q: "Problem: Large numbers of students are failing mathematics. Which is the most reasonable course of action?", o: ["Diagnose the causes and provide remedial teaching.", "Cancel the mathematics tests.", "Pass all students automatically.", "Reduce the syllabus every year."], a: 0, e: "A remedy should remove the cause, not hide the result." },
                { q: "A man walks 5 m north, then 3 m east, then 5 m south. How far and in which direction is he from the start?", o: ["3 m east", "5 m east", "8 m north", "13 m south"], a: 0, e: "The north and south legs cancel, leaving only the 3 m east displacement." },
                { q: "Pointing to a photograph, a man says she is the daughter of my grandfather's only son. How is the woman related to the man?", o: ["Sister", "Aunt", "Mother", "Cousin"], a: 0, e: "The grandfather's only son is the man's father, and his daughter is the man's sister." },
                { q: "If South-East becomes North and North-East becomes West, then West becomes:", o: ["South-East", "North-West", "South", "North-East"], a: 0, e: "The rule rotates every direction by the same amount, which sends West to South-East." },
                { q: "In a row of five people, P is second from the left and Q is fourth from the left. How many people are between P and Q?", o: ["1", "2", "3", "0"], a: 0, e: "Positions 2 and 4 have exactly one position between them." },
                { q: "Five people P, Q, R, S and T sit in a row facing north. P is at the left end, T at the right end, Q is immediately to the right of P, and R is immediately to the left of T. Who is in the middle?", o: ["S", "Q", "R", "P"], a: 0, e: "With P and Q on the left and R and T on the right, the remaining place is S." },
                { q: "A is taller than B. B is taller than C. D is taller than A. Who is the tallest?", o: ["D", "A", "B", "C"], a: 0, e: "The order by height is D, then A, then B, then C." },
                { q: "In a queue, Ravi is 7th from the front and 12th from the back. How many people are in the queue?", o: ["18", "19", "17", "20"], a: 0, e: "Add 7 and 12 and subtract 1 for the person counted twice, giving 18." },
                { q: "If each letter of a word is shifted one place forward, so that CAT becomes DBU, how is DOG coded?", o: ["EPH", "FPI", "CNF", "EOG"], a: 0, e: "Shift each letter forward by one: D-E, O-P, G-H." },
                { q: "If FRIEND is coded as GSJFOE by shifting each letter one place forward, what is the code for CANDLE?", o: ["DBOEMF", "DCOEMF", "DBPEMF", "CBOEMF"], a: 0, e: "Each letter moves forward one: C-D, A-B, N-O, D-E, L-M, E-F." },
                { q: "In a code language, pen is called book, book is called table, and table is called chair. What does one write with?", o: ["book", "table", "chair", "pen"], a: 0, e: "One writes with a pen, and a pen is called a book in this code." },
                { q: "What is the value of x? Statement I: x + y = 10. Statement II: y = 4.", o: ["I alone is sufficient.", "II alone is sufficient.", "Both together are sufficient.", "Neither is sufficient."], a: 2, e: "Statement I alone leaves y unknown, while together they give x = 6." },
                { q: "Is the integer n even? Statement I: n is divisible by 4. Statement II: n is greater than 10.", o: ["I alone is sufficient.", "II alone is sufficient.", "Both together are sufficient.", "Neither is sufficient."], a: 0, e: "Any number divisible by 4 is even, while being greater than 10 says nothing about parity." }
            ];
        }
    }

}
