// HAT course - Verbal drill question bank.
// GENERATED by tools/hat_drill_extract.py from
// content/src/hat_verbal_drill.ch - do not hand-edit.
//
// The text and the answer key are lifted from the printed
// paper in the lesson, so the timed runner and the answer
// key can never disagree.
//
// Shape: { q, o, a, e }
//   q  question text
//   o  options in order
//   a  index of the correct option
//   e  why that option is right and the trap is wrong
public namespace underlayer_content {

    public func render_hat_verbal_drill_bank(page : &mut HtmlPage) {
        #js {
            var HAT_VERBAL_DRILL_BANK = [
                { q: "LUCID most nearly means:", o: ["dim", "loud", "clear", "confused"], a: 2, e: "Lucid means clear and easy to understand; dim is the physical sense of light" },
                { q: "Choose the word most nearly opposite to CANDID.", o: ["frank", "honest", "open", "evasive"], a: 3, e: "Candid is frank; evasive is the opposite pole. The other options are synonyms of candid" },
                { q: "GREGARIOUS most nearly means:", o: ["sociable", "solitary", "hostile", "silent"], a: 0, e: "From the root greg, a flock: gregarious people enjoy company" },
                { q: "EPHEMERAL most nearly means:", o: ["eternal", "fragile", "short-lived", "costly"], a: 2, e: "Ephemeral is lasting a very short time; fragile is about breaking, not lasting" },
                { q: "MITIGATE most nearly means:", o: ["to worsen", "to measure", "to deny", "to lessen"], a: 3, e: "Mitigate means to make less severe; its opposite pole is exacerbate" },
                { q: "PARSIMONIOUS most nearly means:", o: ["stingy", "generous", "wealthy", "wasteful"], a: 0, e: "Parsimonious is excessively sparing with money; wasteful is its opposite" },
                { q: "Choose the word most nearly opposite to DILIGENT.", o: ["hard-working", "careful", "indolent", "punctual"], a: 2, e: "Diligent means hard-working; indolent means lazy. Option (a) is a synonym" },
                { q: "PREVALENT most nearly means:", o: ["rare", "ancient", "valuable", "widespread"], a: 3, e: "Prevalent means common or widespread; rare is its opposite" },
                { q: "PEN : WRITE :: KNIFE : ?", o: ["sharp", "cut", "kitchen", "metal"], a: 1, e: "Object to the action it performs: a pen writes, a knife cuts" },
                { q: "DOCTOR : PATIENT :: LAWYER : ?", o: ["court", "judge", "client", "law"], a: 2, e: "Professional to the person served: a doctor has patients, a lawyer has clients" },
                { q: "SCALE : WEIGHT :: THERMOMETER : ?", o: ["temperature", "mercury", "degrees", "heat"], a: 0, e: "Instrument to the quantity it measures; mercury is what it contains, degrees the unit" },
                { q: "STARVATION : FOOD :: DEHYDRATION : ?", o: ["thirst", "desert", "heat", "water"], a: 3, e: "Condition to what is lacking: starvation is the lack of food, dehydration of water" },
                { q: "CHAPTER : BOOK :: ACT : ?", o: ["scene", "play", "actor", "stage"], a: 1, e: "Part to whole: a chapter is part of a book, an act is part of a play. Option (a) scene reverses the relation" },
                { q: "Although the plan was ambitious, it was ___.", o: ["practical", "approved", "economical", "impractical"], a: 3, e: "Although signals contrast, so the blank opposes ambitious" },
                { q: "The professor was known for her ___ lectures: no student ever needed to ask for clarification.", o: ["lucid", "convoluted", "lengthy", "dull"], a: 0, e: "The colon explains: no one needed clarification because the lectures were clear" },
                { q: "He was ___ in his praise, offering only the faintest compliments.", o: ["lavish", "excessive", "sparing", "sincere"], a: 2, e: "Faint compliments mean praise given reluctantly, that is sparing" },
                { q: "Because the evidence was ___, the court dismissed the case.", o: ["conclusive", "insufficient", "overwhelming", "documented"], a: 1, e: "Dismissal follows from evidence that was not enough; conclusive and overwhelming point the other way" },
                { q: "The team worked ___, finishing every task two days before the deadline.", o: ["negligently", "reluctantly", "nervously", "diligently"], a: 3, e: "Finishing early indicates hard work, not reluctance or negligence" },
                { q: "The decision was unanimous; every member ___.", o: ["agreed", "objected", "abstained", "hesitated"], a: 0, e: "Unanimous means all in agreement, so every member agreed" },
                { q: "The list of items ___ long.", o: ["are", "have", "is", "were"], a: 2, e: "The subject is the singular list; items sits inside a prepositional phrase" },
                { q: "Neither the manager nor the clerks ___ ready when the audit began.", o: ["was", "were", "is", "has been"], a: 1, e: "With neither ... nor the verb follows the nearer subject, which is the plural clerks" },
                { q: "Find the error: 'She is senior than me in the department.'", o: ["senior", "me", "than", "no error"], a: 2, e: "Senior takes to, never than: senior to me" },
                { q: "Which sentence is grammatically correct?", o: ["Each of the candidates has submitted a form", "Walking down the corridor, the report was found", "Ten kilometres are a long walk", "A number of students was absent"], a: 0, e: "Each is singular so has is right. (b) dangles, (c) treats a distance as plural, (d) needs were" },
                { q: "All staff must comply ___ the new rules.", o: ["to", "by", "for", "with"], a: 3, e: "Comply with is the fixed pairing" },
                { q: "The delay had no ___ on the final schedule.", o: ["effect", "affect", "effort", "affected"], a: 0, e: "A noun is required after had no; affect is the verb" },
                { q: "She is not afraid ___ criticism.", o: ["from", "to", "of", "with"], a: 2, e: "Afraid of, like aware of and capable of" },
                { q: "The passage is chiefly concerned with:", o: ["proving that sleep deprivation causes permanent harm", "describing the stages of a normal night's sleep", "showing that laboratory experiments on memory are unreliable", "the association between sleep and the retention of recently learned material"], a: 3, e: "The passage surveys the link between sleep and retention, including a dispute about its cause" },
                { q: "In the experiment described, the participants who stayed awake:", o: ["recalled fewer word pairs", "recalled more word pairs", "slept in the laboratory after testing", "were tested in the evening"], a: 0, e: "The sleepers recalled substantially more, so those who stayed awake recalled fewer" },
                { q: "The rival account is mentioned in order to:", o: ["show that the experiment was fabricated", "explain why slow-wave sleep matters", "present an alternative explanation of the same result", "argue that memory cannot be studied at all"], a: 2, e: "The interference account offers a different explanation of the same finding" },
                { q: "Which statement is best supported by the passage?", o: ["Slow-wave sleep is the only stage that affects memory", "Studying shortly before sleep may improve later recall", "The two explanations have been fully distinguished", "Sleep has no measurable effect on learning"], a: 1, e: "The closing sentence states that material learned shortly before sleep survives better. The others overreach: only, fully and no measurable effect are not supported" }
            ];
        }
    }

}
