// HAT course - Quantitative drill question bank.
// GENERATED by tools/hat_drill_extract.py from
// content/src/hat_quant_drill.ch - do not hand-edit.
//
// The text and the answer key are lifted from the printed
// paper in the lesson, so the timed runner and the answer
// key can never disagree.
//
// Shape: { q, o, a, e }
//   q  question text
//   o  options in order
//   a  index of the correct option
//   e  why that option is right and the trap is wrong
public namespace underlayer_content {

    public func render_hat_quant_drill_bank(page : &mut HtmlPage) {
        #js {
            var HAT_QUANT_DRILL_BANK = [
                { q: "What is 15 percent of 240?", o: ["24", "36", "45", "16"], a: 1, e: "10 percent is 24 and 5 percent is 12, so 15 percent is 36" },
                { q: "A price rises from Rs 80 to Rs 100. What is the percentage increase?", o: ["20 percent", "25 percent", "80 percent", "12.5 percent"], a: 1, e: "Change 20 divided by original 80" },
                { q: "Divide Rs 180 in the ratio 2 : 3 : 4. What is the largest share?", o: ["Rs 40", "Rs 60", "Rs 80", "Rs 90"], a: 2, e: "Parts total 9, one part is 20, largest is 4 parts" },
                { q: "Three workers finish a job in 12 days. How long will four workers take at the same rate?", o: ["8 days", "9 days", "16 days", "48 days"], a: 1, e: "36 worker-days over 4 workers" },
                { q: "Solve for x: 3x + 7 = 22.", o: ["3", "5", "15", "9.67"], a: 1, e: "3x = 15, so x = 5" },
                { q: "What is the area of a triangle with base 10 cm and height 6 cm?", o: ["30 cm^2", "60 cm^2", "16 cm^2", "80 cm^2"], a: 0, e: "One half of 10 x 6" },
                { q: "What is the mean of 4, 8, 10 and 14?", o: ["8", "9", "12", "36"], a: 1, e: "Sum 36 over 4 values" },
                { q: "A fair six-sided die is rolled once. What is the probability of an even number?", o: ["1/6", "1/3", "1/2", "2/3"], a: 2, e: "Three even faces out of six" },
                { q: "What is the HCF of 84 and 126?", o: ["21", "42", "252", "10,584"], a: 1, e: "84 = 2^2x3x7 and 126 = 2x3^2x7, so HCF = 2x3x7" },
                { q: "What is the units digit of 2^(35)?", o: ["2", "4", "6", "8"], a: 3, e: "The cycle 2, 4, 8, 6 has length 4 and 35 leaves remainder 3" },
                { q: "Which fraction is larger, 7/12 or 11/19?", o: ["7/12", "11/19", "they are equal", "cannot be determined"], a: 0, e: "7 x 19 = 133 against 11 x 12 = 132" },
                { q: "The mean of 12 numbers is 15. If the number 27 is removed, what is the new mean?", o: ["13.9", "12.75", "14.5", "15"], a: 0, e: "Total 180 minus 27 is 153 over 11 values" },
                { q: "A train 120 m long travels at 54 km/h. How long does it take to cross a platform 180 m long?", o: ["8 s", "12 s", "20 s", "30 s"], a: 2, e: "54 km/h is 15 m/s; 120 + 180 = 300 m" },
                { q: "A boat covers 12 km downstream in 1 hour and the same distance upstream in 2 hours. What is its speed in still water?", o: ["3 km/h", "6 km/h", "9 km/h", "12 km/h"], a: 2, e: "Downstream 12, upstream 6, so still water is their average" },
                { q: "A can do a job in 12 days and B in 18 days. Working together, how long will they take?", o: ["6 days", "7.2 days", "15 days", "30 days"], a: 1, e: "1/12 + 1/18 = 5/36, so the time is 36/5" },
                { q: "An inlet pipe fills a tank in 6 hours and a drain empties it in 9 hours. With both open, how long does the tank take to fill?", o: ["3 h", "7.2 h", "15 h", "18 h"], a: 3, e: "1/6 - 1/9 = 1/18" },
                { q: "Twelve workers complete a job in 15 days. How long would nine workers take at the same rate?", o: ["11.25 days", "16.5 days", "20 days", "28 days"], a: 2, e: "180 worker-days over 9 workers" },
                { q: "Two fair dice are rolled. What is the probability that the sum is 8?", o: ["1/6", "1/9", "5/36", "4/36"], a: 2, e: "Five pairs: (2,6), (3,5), (4,4), (5,3), (6,2)" },
                { q: "A bag holds 4 red and 6 blue balls. Two are drawn without replacement. What is the probability that both are red?", o: ["4/25", "2/15", "1/5", "3/10"], a: 1, e: "(4/10) x (3/9) = 12/90" },
                { q: "A value falls by 20 percent and then rises by 20 percent. Compared with its starting value it is:", o: ["unchanged", "4 percent lower", "4 percent higher", "2 percent lower"], a: 1, e: "100 becomes 80, then 96, because the rise is on a smaller base" },
                { q: "Enrolment rises from 300 to 350 students. What is the percentage increase?", o: ["14.3 percent", "16.7 percent", "25 percent", "50 percent"], a: 1, e: "50 divided by the original 300" },
                { q: "What is the simple interest on Rs 5,000 at 8 percent per year for 2 years?", o: ["Rs 400", "Rs 800", "Rs 1,000", "Rs 5,800"], a: 1, e: "5,000 x 8 percent x 2 years" },
                { q: "A car covers 150 km in 2 hours 30 minutes. What is its average speed?", o: ["55 km/h", "60 km/h", "75 km/h", "100 km/h"], a: 1, e: "2 h 30 min is 2.5 hours" },
                { q: "A cyclist covers the first half of a journey at 10 km/h and the second half at 15 km/h. What is the average speed for the whole journey?", o: ["12 km/h", "12.5 km/h", "13 km/h", "25 km/h"], a: 0, e: "Equal distances give 2ab / (a + b) = 300 / 25" },
                { q: "In how many ways can a committee of 3 be chosen from 7 people?", o: ["21", "35", "210", "343"], a: 1, e: "7 x 6 x 5 / 3! = 210 / 6" }
            ];
        }
    }

}
